# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'app.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QLabel,
    QMainWindow, QMenuBar, QPushButton, QScrollArea,
    QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1127, 598)
        font = QFont()
        font.setFamilies([u"The Juke Box"])
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frontage = QLabel(self.centralwidget)
        self.frontage.setObjectName(u"frontage")
        self.frontage.setGeometry(QRect(70, -140, 1000, 752))
        font1 = QFont()
        font1.setFamilies([u"A little sunshine"])
        self.frontage.setFont(font1)
        self.frontage.setPixmap(QPixmap(u"resources/frontage-template.png"))
        self.frontage.setScaledContents(True)
        self.buttons = QFrame(self.centralwidget)
        self.buttons.setObjectName(u"buttons")
        self.buttons.setGeometry(QRect(570, 110, 91, 281))
        self.buttons.setStyleSheet(u"background:transparent")
        self.buttons.setFrameShape(QFrame.Shape.StyledPanel)
        self.buttons.setFrameShadow(QFrame.Shadow.Raised)
        self.buttonforward = QPushButton(self.buttons)
        self.buttonforward.setObjectName(u"buttonforward")
        self.buttonforward.setGeometry(QRect(54, 247, 30, 30))
        font2 = QFont()
        font2.setFamilies([u"Love Craft"])
        self.buttonforward.setFont(font2)
        self.buttonforward.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.buttonforward.setAutoFillBackground(False)
        self.buttonforward.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"border-radius: 15px;")
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.GoNext))
        self.buttonforward.setIcon(icon)
        self.buttonbackward = QPushButton(self.buttons)
        self.buttonbackward.setObjectName(u"buttonbackward")
        self.buttonbackward.setGeometry(QRect(-1, 248, 30, 30))
        self.buttonbackward.setFont(font2)
        self.buttonbackward.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.buttonbackward.setAutoFillBackground(False)
        self.buttonbackward.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"border-radius: 15px;")
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.GoPrevious))
        self.buttonbackward.setIcon(icon1)
        self.button5 = QPushButton(self.buttons)
        self.button5.setObjectName(u"button5")
        self.button5.setGeometry(QRect(0, 197, 30, 30))
        self.button5.setFont(font2)
        self.button5.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.button5.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"border-radius: 15px;")
        self.button0 = QPushButton(self.buttons)
        self.button0.setObjectName(u"button0")
        self.button0.setGeometry(QRect(54, 197, 30, 30))
        self.button0.setFont(font2)
        self.button0.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.button0.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"border-radius: 15px;")
        self.button4 = QPushButton(self.buttons)
        self.button4.setObjectName(u"button4")
        self.button4.setGeometry(QRect(1, 149, 30, 30))
        self.button4.setFont(font2)
        self.button4.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.button4.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"border-radius: 15px;")
        self.button9 = QPushButton(self.buttons)
        self.button9.setObjectName(u"button9")
        self.button9.setGeometry(QRect(54, 149, 30, 30))
        self.button9.setFont(font2)
        self.button9.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.button9.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"border-radius: 15px;")
        self.button3 = QPushButton(self.buttons)
        self.button3.setObjectName(u"button3")
        self.button3.setGeometry(QRect(1, 101, 30, 30))
        self.button3.setFont(font2)
        self.button3.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.button3.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"border-radius: 15px;")
        self.button8 = QPushButton(self.buttons)
        self.button8.setObjectName(u"button8")
        self.button8.setGeometry(QRect(54, 101, 30, 30))
        self.button8.setFont(font2)
        self.button8.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.button8.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"border-radius: 15px;")
        self.button2 = QPushButton(self.buttons)
        self.button2.setObjectName(u"button2")
        self.button2.setGeometry(QRect(1, 50, 30, 30))
        self.button2.setFont(font2)
        self.button2.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.button2.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"border-radius: 15px;")
        self.button1 = QPushButton(self.buttons)
        self.button1.setObjectName(u"button1")
        self.button1.setGeometry(QRect(2, 2, 30, 30))
        self.button1.setFont(font2)
        self.button1.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.button1.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"border-radius: 15px;")
        self.button1.setFlat(False)
        self.button6 = QPushButton(self.buttons)
        self.button6.setObjectName(u"button6")
        self.button6.setGeometry(QRect(55, 3, 30, 30))
        self.button6.setFont(font2)
        self.button6.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.button6.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"border-radius: 15px;")
        self.button7 = QPushButton(self.buttons)
        self.button7.setObjectName(u"button7")
        self.button7.setGeometry(QRect(55, 52, 30, 30))
        self.button7.setFont(font2)
        self.button7.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.button7.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"border-radius: 15px;")
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(204, 131, 130, 41))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setStyleSheet(u"background: transparent; border:none;")
        self.scrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 143, 33))
        self.horizontalLayout = QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.song0 = QLabel(self.scrollAreaWidgetContents)
        self.song0.setObjectName(u"song0")
        font3 = QFont()
        font3.setFamilies([u"Arcane Nine"])
        font3.setPointSize(18)
        self.song0.setFont(font3)
        self.song0.setStyleSheet(u"background-color:yellow")
        self.song0.setWordWrap(False)

        self.horizontalLayout.addWidget(self.song0)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_2 = QScrollArea(self.centralwidget)
        self.scrollArea_2.setObjectName(u"scrollArea_2")
        self.scrollArea_2.setGeometry(QRect(202, 177, 130, 41))
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setStyleSheet(u"background: transparent; border:none;")
        self.scrollArea_2.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_2.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollAreaWidgetContents_5 = QWidget()
        self.scrollAreaWidgetContents_5.setObjectName(u"scrollAreaWidgetContents_5")
        self.scrollAreaWidgetContents_5.setGeometry(QRect(0, 0, 132, 33))
        self.horizontalLayout_5 = QHBoxLayout(self.scrollAreaWidgetContents_5)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.song1 = QLabel(self.scrollAreaWidgetContents_5)
        self.song1.setObjectName(u"song1")
        self.song1.setFont(font3)
        self.song1.setStyleSheet(u"background-color:yellow")

        self.horizontalLayout_5.addWidget(self.song1)

        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_5)
        self.scrollArea_3 = QScrollArea(self.centralwidget)
        self.scrollArea_3.setObjectName(u"scrollArea_3")
        self.scrollArea_3.setGeometry(QRect(202, 221, 130, 41))
        sizePolicy.setHeightForWidth(self.scrollArea_3.sizePolicy().hasHeightForWidth())
        self.scrollArea_3.setSizePolicy(sizePolicy)
        self.scrollArea_3.setStyleSheet(u"background: transparent; border:none;")
        self.scrollArea_3.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_3.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollAreaWidgetContents_7 = QWidget()
        self.scrollAreaWidgetContents_7.setObjectName(u"scrollAreaWidgetContents_7")
        self.scrollAreaWidgetContents_7.setGeometry(QRect(0, 0, 132, 33))
        self.horizontalLayout_6 = QHBoxLayout(self.scrollAreaWidgetContents_7)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.song2 = QLabel(self.scrollAreaWidgetContents_7)
        self.song2.setObjectName(u"song2")
        self.song2.setFont(font3)
        self.song2.setStyleSheet(u"background-color:yellow")

        self.horizontalLayout_6.addWidget(self.song2)

        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_7)
        self.scrollArea_4 = QScrollArea(self.centralwidget)
        self.scrollArea_4.setObjectName(u"scrollArea_4")
        self.scrollArea_4.setGeometry(QRect(201, 267, 130, 41))
        sizePolicy.setHeightForWidth(self.scrollArea_4.sizePolicy().hasHeightForWidth())
        self.scrollArea_4.setSizePolicy(sizePolicy)
        self.scrollArea_4.setStyleSheet(u"background: transparent; border:none;")
        self.scrollArea_4.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_4.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollAreaWidgetContents_8 = QWidget()
        self.scrollAreaWidgetContents_8.setObjectName(u"scrollAreaWidgetContents_8")
        self.scrollAreaWidgetContents_8.setGeometry(QRect(0, 0, 132, 33))
        self.horizontalLayout_7 = QHBoxLayout(self.scrollAreaWidgetContents_8)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.song3 = QLabel(self.scrollAreaWidgetContents_8)
        self.song3.setObjectName(u"song3")
        self.song3.setFont(font3)
        self.song3.setStyleSheet(u"background-color:yellow")

        self.horizontalLayout_7.addWidget(self.song3)

        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_8)
        self.scrollArea_5 = QScrollArea(self.centralwidget)
        self.scrollArea_5.setObjectName(u"scrollArea_5")
        self.scrollArea_5.setGeometry(QRect(198, 312, 130, 41))
        sizePolicy.setHeightForWidth(self.scrollArea_5.sizePolicy().hasHeightForWidth())
        self.scrollArea_5.setSizePolicy(sizePolicy)
        self.scrollArea_5.setStyleSheet(u"background: transparent; border:none;")
        self.scrollArea_5.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_5.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollAreaWidgetContents_9 = QWidget()
        self.scrollAreaWidgetContents_9.setObjectName(u"scrollAreaWidgetContents_9")
        self.scrollAreaWidgetContents_9.setGeometry(QRect(0, 0, 132, 33))
        self.horizontalLayout_8 = QHBoxLayout(self.scrollAreaWidgetContents_9)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.song4 = QLabel(self.scrollAreaWidgetContents_9)
        self.song4.setObjectName(u"song4")
        self.song4.setFont(font3)
        self.song4.setStyleSheet(u"background-color:yellow")

        self.horizontalLayout_8.addWidget(self.song4)

        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_9)
        self.scrollArea_6 = QScrollArea(self.centralwidget)
        self.scrollArea_6.setObjectName(u"scrollArea_6")
        self.scrollArea_6.setGeometry(QRect(198, 358, 130, 41))
        sizePolicy.setHeightForWidth(self.scrollArea_6.sizePolicy().hasHeightForWidth())
        self.scrollArea_6.setSizePolicy(sizePolicy)
        self.scrollArea_6.setStyleSheet(u"background: transparent; border:none;")
        self.scrollArea_6.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_6.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollAreaWidgetContents_10 = QWidget()
        self.scrollAreaWidgetContents_10.setObjectName(u"scrollAreaWidgetContents_10")
        self.scrollAreaWidgetContents_10.setGeometry(QRect(0, 0, 132, 33))
        self.horizontalLayout_9 = QHBoxLayout(self.scrollAreaWidgetContents_10)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.song5 = QLabel(self.scrollAreaWidgetContents_10)
        self.song5.setObjectName(u"song5")
        self.song5.setFont(font3)
        self.song5.setStyleSheet(u"background-color:yellow")

        self.horizontalLayout_9.addWidget(self.song5)

        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_10)
        self.scrollArea_7 = QScrollArea(self.centralwidget)
        self.scrollArea_7.setObjectName(u"scrollArea_7")
        self.scrollArea_7.setGeometry(QRect(383, 269, 130, 41))
        sizePolicy.setHeightForWidth(self.scrollArea_7.sizePolicy().hasHeightForWidth())
        self.scrollArea_7.setSizePolicy(sizePolicy)
        self.scrollArea_7.setStyleSheet(u"background: transparent; border:none;")
        self.scrollArea_7.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_7.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollAreaWidgetContents_22 = QWidget()
        self.scrollAreaWidgetContents_22.setObjectName(u"scrollAreaWidgetContents_22")
        self.scrollAreaWidgetContents_22.setGeometry(QRect(0, 0, 132, 33))
        self.horizontalLayout_21 = QHBoxLayout(self.scrollAreaWidgetContents_22)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName(u"horizontalLayout_21")
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.song9 = QLabel(self.scrollAreaWidgetContents_22)
        self.song9.setObjectName(u"song9")
        self.song9.setFont(font3)
        self.song9.setStyleSheet(u"background-color:yellow")

        self.horizontalLayout_21.addWidget(self.song9)

        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_22)
        self.scrollArea_8 = QScrollArea(self.centralwidget)
        self.scrollArea_8.setObjectName(u"scrollArea_8")
        self.scrollArea_8.setGeometry(QRect(384, 224, 130, 41))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.scrollArea_8.sizePolicy().hasHeightForWidth())
        self.scrollArea_8.setSizePolicy(sizePolicy1)
        self.scrollArea_8.setStyleSheet(u"background: transparent; border:none;")
        self.scrollArea_8.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_8.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_8.setWidgetResizable(True)
        self.scrollAreaWidgetContents_23 = QWidget()
        self.scrollAreaWidgetContents_23.setObjectName(u"scrollAreaWidgetContents_23")
        self.scrollAreaWidgetContents_23.setGeometry(QRect(0, 0, 132, 33))
        self.horizontalLayout_22 = QHBoxLayout(self.scrollAreaWidgetContents_23)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName(u"horizontalLayout_22")
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.song8 = QLabel(self.scrollAreaWidgetContents_23)
        self.song8.setObjectName(u"song8")
        self.song8.setFont(font3)
        self.song8.setStyleSheet(u"background-color:yellow")

        self.horizontalLayout_22.addWidget(self.song8)

        self.scrollArea_8.setWidget(self.scrollAreaWidgetContents_23)
        self.scrollArea_9 = QScrollArea(self.centralwidget)
        self.scrollArea_9.setObjectName(u"scrollArea_9")
        self.scrollArea_9.setGeometry(QRect(383, 315, 130, 41))
        sizePolicy.setHeightForWidth(self.scrollArea_9.sizePolicy().hasHeightForWidth())
        self.scrollArea_9.setSizePolicy(sizePolicy)
        self.scrollArea_9.setStyleSheet(u"background: transparent; border:none;")
        self.scrollArea_9.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_9.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_9.setWidgetResizable(True)
        self.scrollAreaWidgetContents_24 = QWidget()
        self.scrollAreaWidgetContents_24.setObjectName(u"scrollAreaWidgetContents_24")
        self.scrollAreaWidgetContents_24.setGeometry(QRect(0, 0, 132, 33))
        self.horizontalLayout_23 = QHBoxLayout(self.scrollAreaWidgetContents_24)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName(u"horizontalLayout_23")
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.song10 = QLabel(self.scrollAreaWidgetContents_24)
        self.song10.setObjectName(u"song10")
        self.song10.setFont(font3)
        self.song10.setStyleSheet(u"background-color:yellow")

        self.horizontalLayout_23.addWidget(self.song10)

        self.scrollArea_9.setWidget(self.scrollAreaWidgetContents_24)
        self.scrollArea_10 = QScrollArea(self.centralwidget)
        self.scrollArea_10.setObjectName(u"scrollArea_10")
        self.scrollArea_10.setGeometry(QRect(383, 361, 130, 41))
        sizePolicy.setHeightForWidth(self.scrollArea_10.sizePolicy().hasHeightForWidth())
        self.scrollArea_10.setSizePolicy(sizePolicy)
        self.scrollArea_10.setStyleSheet(u"background: transparent; border:none;")
        self.scrollArea_10.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_10.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_10.setWidgetResizable(True)
        self.scrollAreaWidgetContents_25 = QWidget()
        self.scrollAreaWidgetContents_25.setObjectName(u"scrollAreaWidgetContents_25")
        self.scrollAreaWidgetContents_25.setGeometry(QRect(0, 0, 132, 33))
        self.horizontalLayout_24 = QHBoxLayout(self.scrollAreaWidgetContents_25)
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName(u"horizontalLayout_24")
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.song11 = QLabel(self.scrollAreaWidgetContents_25)
        self.song11.setObjectName(u"song11")
        self.song11.setFont(font3)
        self.song11.setStyleSheet(u"background-color:yellow")

        self.horizontalLayout_24.addWidget(self.song11)

        self.scrollArea_10.setWidget(self.scrollAreaWidgetContents_25)
        self.scrollArea_11 = QScrollArea(self.centralwidget)
        self.scrollArea_11.setObjectName(u"scrollArea_11")
        self.scrollArea_11.setGeometry(QRect(383, 180, 130, 41))
        sizePolicy.setHeightForWidth(self.scrollArea_11.sizePolicy().hasHeightForWidth())
        self.scrollArea_11.setSizePolicy(sizePolicy)
        self.scrollArea_11.setStyleSheet(u"background: transparent; border:none;")
        self.scrollArea_11.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_11.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_11.setWidgetResizable(True)
        self.scrollAreaWidgetContents_26 = QWidget()
        self.scrollAreaWidgetContents_26.setObjectName(u"scrollAreaWidgetContents_26")
        self.scrollAreaWidgetContents_26.setGeometry(QRect(0, 0, 132, 33))
        self.horizontalLayout_25 = QHBoxLayout(self.scrollAreaWidgetContents_26)
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setObjectName(u"horizontalLayout_25")
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.song7 = QLabel(self.scrollAreaWidgetContents_26)
        self.song7.setObjectName(u"song7")
        self.song7.setFont(font3)
        self.song7.setStyleSheet(u"background-color:yellow")

        self.horizontalLayout_25.addWidget(self.song7)

        self.scrollArea_11.setWidget(self.scrollAreaWidgetContents_26)
        self.scrollArea_12 = QScrollArea(self.centralwidget)
        self.scrollArea_12.setObjectName(u"scrollArea_12")
        self.scrollArea_12.setGeometry(QRect(383, 136, 130, 41))
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.scrollArea_12.sizePolicy().hasHeightForWidth())
        self.scrollArea_12.setSizePolicy(sizePolicy2)
        self.scrollArea_12.setStyleSheet(u"background: transparent; border:none;")
        self.scrollArea_12.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_12.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_12.setWidgetResizable(True)
        self.scrollAreaWidgetContents_27 = QWidget()
        self.scrollAreaWidgetContents_27.setObjectName(u"scrollAreaWidgetContents_27")
        self.scrollAreaWidgetContents_27.setGeometry(QRect(0, 0, 132, 33))
        self.horizontalLayout_26 = QHBoxLayout(self.scrollAreaWidgetContents_27)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName(u"horizontalLayout_26")
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.song6 = QLabel(self.scrollAreaWidgetContents_27)
        self.song6.setObjectName(u"song6")
        self.song6.setFont(font3)
        self.song6.setStyleSheet(u"background-color:yellow")

        self.horizontalLayout_26.addWidget(self.song6)

        self.scrollArea_12.setWidget(self.scrollAreaWidgetContents_27)
        self.num = QLabel(self.centralwidget)
        self.num.setObjectName(u"num")
        self.num.setGeometry(QRect(345, 136, 40, 27))
        self.num.setFont(font3)
        self.num.setStyleSheet(u"background-color:yellow")
        self.num_2 = QLabel(self.centralwidget)
        self.num_2.setObjectName(u"num_2")
        self.num_2.setGeometry(QRect(163, 177, 40, 27))
        self.num_2.setFont(font3)
        self.num_2.setStyleSheet(u"background-color:yellow")
        self.num_3 = QLabel(self.centralwidget)
        self.num_3.setObjectName(u"num_3")
        self.num_3.setGeometry(QRect(165, 131, 40, 27))
        self.num_3.setFont(font3)
        self.num_3.setStyleSheet(u"background-color:yellow")
        self.num_4 = QLabel(self.centralwidget)
        self.num_4.setObjectName(u"num_4")
        self.num_4.setGeometry(QRect(163, 221, 40, 27))
        self.num_4.setFont(font3)
        self.num_4.setStyleSheet(u"background-color:yellow")
        self.num_5 = QLabel(self.centralwidget)
        self.num_5.setObjectName(u"num_5")
        self.num_5.setGeometry(QRect(162, 267, 40, 27))
        self.num_5.setFont(font3)
        self.num_5.setStyleSheet(u"background-color:yellow")
        self.num_6 = QLabel(self.centralwidget)
        self.num_6.setObjectName(u"num_6")
        self.num_6.setGeometry(QRect(159, 312, 40, 27))
        self.num_6.setFont(font3)
        self.num_6.setStyleSheet(u"background-color:yellow")
        self.num_7 = QLabel(self.centralwidget)
        self.num_7.setObjectName(u"num_7")
        self.num_7.setGeometry(QRect(159, 358, 40, 27))
        self.num_7.setFont(font3)
        self.num_7.setStyleSheet(u"background-color:yellow")
        self.num_8 = QLabel(self.centralwidget)
        self.num_8.setObjectName(u"num_8")
        self.num_8.setGeometry(QRect(344, 180, 40, 27))
        self.num_8.setFont(font3)
        self.num_8.setStyleSheet(u"background-color:yellow")
        self.num_9 = QLabel(self.centralwidget)
        self.num_9.setObjectName(u"num_9")
        self.num_9.setGeometry(QRect(345, 224, 40, 27))
        self.num_9.setFont(font3)
        self.num_9.setStyleSheet(u"background-color:yellow")
        self.num_10 = QLabel(self.centralwidget)
        self.num_10.setObjectName(u"num_10")
        self.num_10.setGeometry(QRect(344, 269, 40, 27))
        self.num_10.setFont(font3)
        self.num_10.setStyleSheet(u"background-color:yellow")
        self.num_11 = QLabel(self.centralwidget)
        self.num_11.setObjectName(u"num_11")
        self.num_11.setGeometry(QRect(344, 316, 40, 27))
        self.num_11.setFont(font3)
        self.num_11.setStyleSheet(u"background-color:yellow")
        self.num_12 = QLabel(self.centralwidget)
        self.num_12.setObjectName(u"num_12")
        self.num_12.setGeometry(QRect(344, 361, 40, 27))
        self.num_12.setFont(font3)
        self.num_12.setStyleSheet(u"background-color:yellow")
        self.scrollArea_13 = QScrollArea(self.centralwidget)
        self.scrollArea_13.setObjectName(u"scrollArea_13")
        self.scrollArea_13.setGeometry(QRect(748, 281, 130, 41))
        sizePolicy.setHeightForWidth(self.scrollArea_13.sizePolicy().hasHeightForWidth())
        self.scrollArea_13.setSizePolicy(sizePolicy)
        self.scrollArea_13.setStyleSheet(u"background: transparent; border:none;")
        self.scrollArea_13.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_13.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_13.setWidgetResizable(True)
        self.scrollAreaWidgetContents_28 = QWidget()
        self.scrollAreaWidgetContents_28.setObjectName(u"scrollAreaWidgetContents_28")
        self.scrollAreaWidgetContents_28.setGeometry(QRect(0, 0, 132, 33))
        self.horizontalLayout_27 = QHBoxLayout(self.scrollAreaWidgetContents_28)
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setObjectName(u"horizontalLayout_27")
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.song15 = QLabel(self.scrollAreaWidgetContents_28)
        self.song15.setObjectName(u"song15")
        self.song15.setFont(font3)
        self.song15.setStyleSheet(u"background-color:yellow")

        self.horizontalLayout_27.addWidget(self.song15)

        self.scrollArea_13.setWidget(self.scrollAreaWidgetContents_28)
        self.num_13 = QLabel(self.centralwidget)
        self.num_13.setObjectName(u"num_13")
        self.num_13.setGeometry(QRect(891, 375, 40, 27))
        self.num_13.setFont(font3)
        self.num_13.setStyleSheet(u"background-color:yellow")
        self.num_14 = QLabel(self.centralwidget)
        self.num_14.setObjectName(u"num_14")
        self.num_14.setGeometry(QRect(892, 150, 40, 27))
        self.num_14.setFont(font3)
        self.num_14.setStyleSheet(u"background-color:yellow")
        self.scrollArea_14 = QScrollArea(self.centralwidget)
        self.scrollArea_14.setObjectName(u"scrollArea_14")
        self.scrollArea_14.setGeometry(QRect(930, 375, 130, 41))
        sizePolicy.setHeightForWidth(self.scrollArea_14.sizePolicy().hasHeightForWidth())
        self.scrollArea_14.setSizePolicy(sizePolicy)
        self.scrollArea_14.setStyleSheet(u"background: transparent; border:none;")
        self.scrollArea_14.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_14.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_14.setWidgetResizable(True)
        self.scrollAreaWidgetContents_29 = QWidget()
        self.scrollAreaWidgetContents_29.setObjectName(u"scrollAreaWidgetContents_29")
        self.scrollAreaWidgetContents_29.setGeometry(QRect(0, 0, 132, 33))
        self.horizontalLayout_28 = QHBoxLayout(self.scrollAreaWidgetContents_29)
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setObjectName(u"horizontalLayout_28")
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.song23 = QLabel(self.scrollAreaWidgetContents_29)
        self.song23.setObjectName(u"song23")
        self.song23.setFont(font3)
        self.song23.setStyleSheet(u"background-color:yellow")

        self.horizontalLayout_28.addWidget(self.song23)

        self.scrollArea_14.setWidget(self.scrollAreaWidgetContents_29)
        self.num_15 = QLabel(self.centralwidget)
        self.num_15.setObjectName(u"num_15")
        self.num_15.setGeometry(QRect(710, 235, 40, 27))
        self.num_15.setFont(font3)
        self.num_15.setStyleSheet(u"background-color:yellow")
        self.scrollArea_15 = QScrollArea(self.centralwidget)
        self.scrollArea_15.setObjectName(u"scrollArea_15")
        self.scrollArea_15.setGeometry(QRect(930, 283, 130, 41))
        sizePolicy.setHeightForWidth(self.scrollArea_15.sizePolicy().hasHeightForWidth())
        self.scrollArea_15.setSizePolicy(sizePolicy)
        self.scrollArea_15.setStyleSheet(u"background: transparent; border:none;")
        self.scrollArea_15.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_15.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_15.setWidgetResizable(True)
        self.scrollAreaWidgetContents_30 = QWidget()
        self.scrollAreaWidgetContents_30.setObjectName(u"scrollAreaWidgetContents_30")
        self.scrollAreaWidgetContents_30.setGeometry(QRect(0, 0, 132, 33))
        self.horizontalLayout_29 = QHBoxLayout(self.scrollAreaWidgetContents_30)
        self.horizontalLayout_29.setSpacing(0)
        self.horizontalLayout_29.setObjectName(u"horizontalLayout_29")
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.song21 = QLabel(self.scrollAreaWidgetContents_30)
        self.song21.setObjectName(u"song21")
        self.song21.setFont(font3)
        self.song21.setStyleSheet(u"background-color:yellow")

        self.horizontalLayout_29.addWidget(self.song21)

        self.scrollArea_15.setWidget(self.scrollAreaWidgetContents_30)
        self.scrollArea_16 = QScrollArea(self.centralwidget)
        self.scrollArea_16.setObjectName(u"scrollArea_16")
        self.scrollArea_16.setGeometry(QRect(749, 235, 130, 41))
        sizePolicy.setHeightForWidth(self.scrollArea_16.sizePolicy().hasHeightForWidth())
        self.scrollArea_16.setSizePolicy(sizePolicy)
        self.scrollArea_16.setStyleSheet(u"background: transparent; border:none;")
        self.scrollArea_16.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_16.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_16.setWidgetResizable(True)
        self.scrollAreaWidgetContents_31 = QWidget()
        self.scrollAreaWidgetContents_31.setObjectName(u"scrollAreaWidgetContents_31")
        self.scrollAreaWidgetContents_31.setGeometry(QRect(0, 0, 132, 33))
        self.horizontalLayout_30 = QHBoxLayout(self.scrollAreaWidgetContents_31)
        self.horizontalLayout_30.setSpacing(0)
        self.horizontalLayout_30.setObjectName(u"horizontalLayout_30")
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.song14 = QLabel(self.scrollAreaWidgetContents_31)
        self.song14.setObjectName(u"song14")
        self.song14.setFont(font3)
        self.song14.setStyleSheet(u"background-color:yellow")

        self.horizontalLayout_30.addWidget(self.song14)

        self.scrollArea_16.setWidget(self.scrollAreaWidgetContents_31)
        self.num_16 = QLabel(self.centralwidget)
        self.num_16.setObjectName(u"num_16")
        self.num_16.setGeometry(QRect(706, 326, 40, 27))
        self.num_16.setFont(font3)
        self.num_16.setStyleSheet(u"background-color:yellow")
        self.scrollArea_17 = QScrollArea(self.centralwidget)
        self.scrollArea_17.setObjectName(u"scrollArea_17")
        self.scrollArea_17.setGeometry(QRect(931, 238, 130, 41))
        sizePolicy.setHeightForWidth(self.scrollArea_17.sizePolicy().hasHeightForWidth())
        self.scrollArea_17.setSizePolicy(sizePolicy)
        self.scrollArea_17.setStyleSheet(u"background: transparent; border:none;")
        self.scrollArea_17.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_17.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_17.setWidgetResizable(True)
        self.scrollAreaWidgetContents_32 = QWidget()
        self.scrollAreaWidgetContents_32.setObjectName(u"scrollAreaWidgetContents_32")
        self.scrollAreaWidgetContents_32.setGeometry(QRect(0, 0, 132, 33))
        self.horizontalLayout_31 = QHBoxLayout(self.scrollAreaWidgetContents_32)
        self.horizontalLayout_31.setSpacing(0)
        self.horizontalLayout_31.setObjectName(u"horizontalLayout_31")
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.song20 = QLabel(self.scrollAreaWidgetContents_32)
        self.song20.setObjectName(u"song20")
        self.song20.setFont(font3)
        self.song20.setStyleSheet(u"background-color:yellow")

        self.horizontalLayout_31.addWidget(self.song20)

        self.scrollArea_17.setWidget(self.scrollAreaWidgetContents_32)
        self.num_17 = QLabel(self.centralwidget)
        self.num_17.setObjectName(u"num_17")
        self.num_17.setGeometry(QRect(891, 330, 40, 27))
        self.num_17.setFont(font3)
        self.num_17.setStyleSheet(u"background-color:yellow")
        self.num_18 = QLabel(self.centralwidget)
        self.num_18.setObjectName(u"num_18")
        self.num_18.setGeometry(QRect(706, 372, 40, 27))
        self.num_18.setFont(font3)
        self.num_18.setStyleSheet(u"background-color:yellow")
        self.num_19 = QLabel(self.centralwidget)
        self.num_19.setObjectName(u"num_19")
        self.num_19.setGeometry(QRect(710, 191, 40, 27))
        self.num_19.setFont(font3)
        self.num_19.setStyleSheet(u"background-color:yellow")
        self.scrollArea_18 = QScrollArea(self.centralwidget)
        self.scrollArea_18.setObjectName(u"scrollArea_18")
        self.scrollArea_18.setGeometry(QRect(930, 194, 130, 41))
        sizePolicy.setHeightForWidth(self.scrollArea_18.sizePolicy().hasHeightForWidth())
        self.scrollArea_18.setSizePolicy(sizePolicy)
        self.scrollArea_18.setStyleSheet(u"background: transparent; border:none;")
        self.scrollArea_18.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_18.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_18.setWidgetResizable(True)
        self.scrollAreaWidgetContents_33 = QWidget()
        self.scrollAreaWidgetContents_33.setObjectName(u"scrollAreaWidgetContents_33")
        self.scrollAreaWidgetContents_33.setGeometry(QRect(0, 0, 132, 33))
        self.horizontalLayout_32 = QHBoxLayout(self.scrollAreaWidgetContents_33)
        self.horizontalLayout_32.setSpacing(0)
        self.horizontalLayout_32.setObjectName(u"horizontalLayout_32")
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.song19 = QLabel(self.scrollAreaWidgetContents_33)
        self.song19.setObjectName(u"song19")
        self.song19.setFont(font3)
        self.song19.setStyleSheet(u"background-color:yellow")

        self.horizontalLayout_32.addWidget(self.song19)

        self.scrollArea_18.setWidget(self.scrollAreaWidgetContents_33)
        self.num_20 = QLabel(self.centralwidget)
        self.num_20.setObjectName(u"num_20")
        self.num_20.setGeometry(QRect(891, 283, 40, 27))
        self.num_20.setFont(font3)
        self.num_20.setStyleSheet(u"background-color:yellow")
        self.scrollArea_19 = QScrollArea(self.centralwidget)
        self.scrollArea_19.setObjectName(u"scrollArea_19")
        self.scrollArea_19.setGeometry(QRect(745, 326, 130, 41))
        sizePolicy.setHeightForWidth(self.scrollArea_19.sizePolicy().hasHeightForWidth())
        self.scrollArea_19.setSizePolicy(sizePolicy)
        self.scrollArea_19.setStyleSheet(u"background: transparent; border:none;")
        self.scrollArea_19.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_19.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_19.setWidgetResizable(True)
        self.scrollAreaWidgetContents_34 = QWidget()
        self.scrollAreaWidgetContents_34.setObjectName(u"scrollAreaWidgetContents_34")
        self.scrollAreaWidgetContents_34.setGeometry(QRect(0, 0, 132, 33))
        self.horizontalLayout_33 = QHBoxLayout(self.scrollAreaWidgetContents_34)
        self.horizontalLayout_33.setSpacing(0)
        self.horizontalLayout_33.setObjectName(u"horizontalLayout_33")
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.song16 = QLabel(self.scrollAreaWidgetContents_34)
        self.song16.setObjectName(u"song16")
        self.song16.setFont(font3)
        self.song16.setStyleSheet(u"background-color:yellow")

        self.horizontalLayout_33.addWidget(self.song16)

        self.scrollArea_19.setWidget(self.scrollAreaWidgetContents_34)
        self.scrollArea_20 = QScrollArea(self.centralwidget)
        self.scrollArea_20.setObjectName(u"scrollArea_20")
        self.scrollArea_20.setGeometry(QRect(745, 372, 130, 41))
        sizePolicy.setHeightForWidth(self.scrollArea_20.sizePolicy().hasHeightForWidth())
        self.scrollArea_20.setSizePolicy(sizePolicy)
        self.scrollArea_20.setStyleSheet(u"background: transparent; border:none;")
        self.scrollArea_20.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_20.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_20.setWidgetResizable(True)
        self.scrollAreaWidgetContents_35 = QWidget()
        self.scrollAreaWidgetContents_35.setObjectName(u"scrollAreaWidgetContents_35")
        self.scrollAreaWidgetContents_35.setGeometry(QRect(0, 0, 132, 33))
        self.horizontalLayout_34 = QHBoxLayout(self.scrollAreaWidgetContents_35)
        self.horizontalLayout_34.setSpacing(0)
        self.horizontalLayout_34.setObjectName(u"horizontalLayout_34")
        self.horizontalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.song17 = QLabel(self.scrollAreaWidgetContents_35)
        self.song17.setObjectName(u"song17")
        self.song17.setFont(font3)
        self.song17.setStyleSheet(u"background-color:yellow")

        self.horizontalLayout_34.addWidget(self.song17)

        self.scrollArea_20.setWidget(self.scrollAreaWidgetContents_35)
        self.num_21 = QLabel(self.centralwidget)
        self.num_21.setObjectName(u"num_21")
        self.num_21.setGeometry(QRect(709, 281, 40, 27))
        self.num_21.setFont(font3)
        self.num_21.setStyleSheet(u"background-color:yellow")
        self.num_22 = QLabel(self.centralwidget)
        self.num_22.setObjectName(u"num_22")
        self.num_22.setGeometry(QRect(891, 194, 40, 27))
        self.num_22.setFont(font3)
        self.num_22.setStyleSheet(u"background-color:yellow")
        self.num_23 = QLabel(self.centralwidget)
        self.num_23.setObjectName(u"num_23")
        self.num_23.setGeometry(QRect(892, 238, 40, 27))
        self.num_23.setFont(font3)
        self.num_23.setStyleSheet(u"background-color:yellow")
        self.scrollArea_21 = QScrollArea(self.centralwidget)
        self.scrollArea_21.setObjectName(u"scrollArea_21")
        self.scrollArea_21.setGeometry(QRect(749, 191, 130, 41))
        sizePolicy.setHeightForWidth(self.scrollArea_21.sizePolicy().hasHeightForWidth())
        self.scrollArea_21.setSizePolicy(sizePolicy)
        self.scrollArea_21.setStyleSheet(u"background: transparent; border:none;")
        self.scrollArea_21.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_21.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_21.setWidgetResizable(True)
        self.scrollAreaWidgetContents_36 = QWidget()
        self.scrollAreaWidgetContents_36.setObjectName(u"scrollAreaWidgetContents_36")
        self.scrollAreaWidgetContents_36.setGeometry(QRect(0, 0, 132, 33))
        self.horizontalLayout_35 = QHBoxLayout(self.scrollAreaWidgetContents_36)
        self.horizontalLayout_35.setSpacing(0)
        self.horizontalLayout_35.setObjectName(u"horizontalLayout_35")
        self.horizontalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.song13 = QLabel(self.scrollAreaWidgetContents_36)
        self.song13.setObjectName(u"song13")
        self.song13.setFont(font3)
        self.song13.setStyleSheet(u"background-color:yellow")

        self.horizontalLayout_35.addWidget(self.song13)

        self.scrollArea_21.setWidget(self.scrollAreaWidgetContents_36)
        self.num_24 = QLabel(self.centralwidget)
        self.num_24.setObjectName(u"num_24")
        self.num_24.setGeometry(QRect(712, 145, 40, 27))
        self.num_24.setFont(font3)
        self.num_24.setStyleSheet(u"background-color:yellow")
        self.scrollArea_22 = QScrollArea(self.centralwidget)
        self.scrollArea_22.setObjectName(u"scrollArea_22")
        self.scrollArea_22.setGeometry(QRect(930, 329, 130, 41))
        sizePolicy.setHeightForWidth(self.scrollArea_22.sizePolicy().hasHeightForWidth())
        self.scrollArea_22.setSizePolicy(sizePolicy)
        self.scrollArea_22.setStyleSheet(u"background: transparent; border:none;")
        self.scrollArea_22.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_22.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_22.setWidgetResizable(True)
        self.scrollAreaWidgetContents_37 = QWidget()
        self.scrollAreaWidgetContents_37.setObjectName(u"scrollAreaWidgetContents_37")
        self.scrollAreaWidgetContents_37.setGeometry(QRect(0, 0, 132, 33))
        self.horizontalLayout_36 = QHBoxLayout(self.scrollAreaWidgetContents_37)
        self.horizontalLayout_36.setSpacing(0)
        self.horizontalLayout_36.setObjectName(u"horizontalLayout_36")
        self.horizontalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.song22 = QLabel(self.scrollAreaWidgetContents_37)
        self.song22.setObjectName(u"song22")
        self.song22.setFont(font3)
        self.song22.setStyleSheet(u"background-color:yellow")

        self.horizontalLayout_36.addWidget(self.song22)

        self.scrollArea_22.setWidget(self.scrollAreaWidgetContents_37)
        self.scrollArea_23 = QScrollArea(self.centralwidget)
        self.scrollArea_23.setObjectName(u"scrollArea_23")
        self.scrollArea_23.setGeometry(QRect(751, 145, 130, 41))
        sizePolicy.setHeightForWidth(self.scrollArea_23.sizePolicy().hasHeightForWidth())
        self.scrollArea_23.setSizePolicy(sizePolicy)
        self.scrollArea_23.setStyleSheet(u"background: transparent; border:none;")
        self.scrollArea_23.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_23.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_23.setWidgetResizable(True)
        self.scrollAreaWidgetContents_38 = QWidget()
        self.scrollAreaWidgetContents_38.setObjectName(u"scrollAreaWidgetContents_38")
        self.scrollAreaWidgetContents_38.setGeometry(QRect(0, 0, 130, 33))
        self.horizontalLayout_37 = QHBoxLayout(self.scrollAreaWidgetContents_38)
        self.horizontalLayout_37.setSpacing(0)
        self.horizontalLayout_37.setObjectName(u"horizontalLayout_37")
        self.horizontalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.song12 = QLabel(self.scrollAreaWidgetContents_38)
        self.song12.setObjectName(u"song12")
        self.song12.setFont(font3)
        self.song12.setStyleSheet(u"background-color:yellow")
        self.song12.setWordWrap(False)

        self.horizontalLayout_37.addWidget(self.song12)

        self.scrollArea_23.setWidget(self.scrollAreaWidgetContents_38)
        self.scrollArea_24 = QScrollArea(self.centralwidget)
        self.scrollArea_24.setObjectName(u"scrollArea_24")
        self.scrollArea_24.setGeometry(QRect(930, 150, 130, 41))
        sizePolicy.setHeightForWidth(self.scrollArea_24.sizePolicy().hasHeightForWidth())
        self.scrollArea_24.setSizePolicy(sizePolicy)
        self.scrollArea_24.setStyleSheet(u"background: transparent; border:none;")
        self.scrollArea_24.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_24.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_24.setWidgetResizable(True)
        self.scrollAreaWidgetContents_39 = QWidget()
        self.scrollAreaWidgetContents_39.setObjectName(u"scrollAreaWidgetContents_39")
        self.scrollAreaWidgetContents_39.setGeometry(QRect(0, 0, 132, 33))
        self.horizontalLayout_38 = QHBoxLayout(self.scrollAreaWidgetContents_39)
        self.horizontalLayout_38.setSpacing(0)
        self.horizontalLayout_38.setObjectName(u"horizontalLayout_38")
        self.horizontalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.song18 = QLabel(self.scrollAreaWidgetContents_39)
        self.song18.setObjectName(u"song18")
        self.song18.setFont(font3)
        self.song18.setStyleSheet(u"background-color:yellow")

        self.horizontalLayout_38.addWidget(self.song18)

        self.scrollArea_24.setWidget(self.scrollAreaWidgetContents_39)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1127, 30))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.frontage.setText("")
        self.buttonforward.setText("")
        self.buttonbackward.setText("")
        self.button5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.button0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.button4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.button9.setText(QCoreApplication.translate("MainWindow", u"9", None))
        self.button3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.button8.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.button2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.button1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.button6.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.button7.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.song0.setText(QCoreApplication.translate("MainWindow", u"SONG NAME", None))
        self.song1.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song2.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song3.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song4.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song5.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song9.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song8.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song10.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song11.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song7.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song6.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.num.setText(QCoreApplication.translate("MainWindow", u"07: ", None))
        self.num_2.setText(QCoreApplication.translate("MainWindow", u"02: ", None))
        self.num_3.setText(QCoreApplication.translate("MainWindow", u"01: ", None))
        self.num_4.setText(QCoreApplication.translate("MainWindow", u"03: ", None))
        self.num_5.setText(QCoreApplication.translate("MainWindow", u"04: ", None))
        self.num_6.setText(QCoreApplication.translate("MainWindow", u"05: ", None))
        self.num_7.setText(QCoreApplication.translate("MainWindow", u"06: ", None))
        self.num_8.setText(QCoreApplication.translate("MainWindow", u"08: ", None))
        self.num_9.setText(QCoreApplication.translate("MainWindow", u"09: ", None))
        self.num_10.setText(QCoreApplication.translate("MainWindow", u"10: ", None))
        self.num_11.setText(QCoreApplication.translate("MainWindow", u"11:", None))
        self.num_12.setText(QCoreApplication.translate("MainWindow", u"12:", None))
        self.song15.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.num_13.setText(QCoreApplication.translate("MainWindow", u"24:", None))
        self.num_14.setText(QCoreApplication.translate("MainWindow", u"19:", None))
        self.song23.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.num_15.setText(QCoreApplication.translate("MainWindow", u"15:", None))
        self.song21.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song14.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.num_16.setText(QCoreApplication.translate("MainWindow", u"17:", None))
        self.song20.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.num_17.setText(QCoreApplication.translate("MainWindow", u"23:", None))
        self.num_18.setText(QCoreApplication.translate("MainWindow", u"18:", None))
        self.num_19.setText(QCoreApplication.translate("MainWindow", u"14:", None))
        self.song19.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.num_20.setText(QCoreApplication.translate("MainWindow", u"22:", None))
        self.song16.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song17.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.num_21.setText(QCoreApplication.translate("MainWindow", u"16:", None))
        self.num_22.setText(QCoreApplication.translate("MainWindow", u"20:", None))
        self.num_23.setText(QCoreApplication.translate("MainWindow", u"21:", None))
        self.song13.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.num_24.setText(QCoreApplication.translate("MainWindow", u"13:", None))
        self.song22.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song12.setText(QCoreApplication.translate("MainWindow", u"song name", None))
        self.song18.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
    # retranslateUi

