# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'app.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QMainWindow,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1127, 598)
        font = QFont()
        font.setFamilies([u"The Juke Box"])
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frontage = QLabel(self.centralwidget)
        self.frontage.setObjectName(u"frontage")
        self.frontage.setGeometry(QRect(70, -140, 1000, 752))
        font1 = QFont()
        font1.setFamilies([u"A little sunshine"])
        self.frontage.setFont(font1)
        self.frontage.setPixmap(QPixmap(u"resources/frontage-template.png"))
        self.frontage.setScaledContents(True)
        self.song0 = QLabel(self.centralwidget)
        self.song0.setObjectName(u"song0")
        self.song0.setGeometry(QRect(160, 130, 171, 31))
        font2 = QFont()
        font2.setFamilies([u"Arcane Nine"])
        font2.setPointSize(18)
        self.song0.setFont(font2)
        self.song0.setStyleSheet(u"background-color:yellow")
        self.song1 = QLabel(self.centralwidget)
        self.song1.setObjectName(u"song1")
        self.song1.setGeometry(QRect(160, 175, 171, 31))
        self.song1.setFont(font2)
        self.song1.setStyleSheet(u"background-color:yellow")
        self.song2 = QLabel(self.centralwidget)
        self.song2.setObjectName(u"song2")
        self.song2.setGeometry(QRect(160, 220, 171, 31))
        self.song2.setFont(font2)
        self.song2.setStyleSheet(u"background-color:yellow")
        self.song3 = QLabel(self.centralwidget)
        self.song3.setObjectName(u"song3")
        self.song3.setGeometry(QRect(160, 266, 171, 31))
        self.song3.setFont(font2)
        self.song3.setStyleSheet(u"background-color:yellow")
        self.song4 = QLabel(self.centralwidget)
        self.song4.setObjectName(u"song4")
        self.song4.setGeometry(QRect(160, 310, 171, 31))
        self.song4.setFont(font2)
        self.song4.setStyleSheet(u"background-color:yellow")
        self.song5 = QLabel(self.centralwidget)
        self.song5.setObjectName(u"song5")
        self.song5.setGeometry(QRect(160, 357, 171, 31))
        self.song5.setFont(font2)
        self.song5.setStyleSheet(u"background-color:yellow")
        self.song6 = QLabel(self.centralwidget)
        self.song6.setObjectName(u"song6")
        self.song6.setGeometry(QRect(338, 134, 171, 31))
        self.song6.setFont(font2)
        self.song6.setStyleSheet(u"background-color:yellow")
        self.song7 = QLabel(self.centralwidget)
        self.song7.setObjectName(u"song7")
        self.song7.setGeometry(QRect(340, 180, 171, 31))
        self.song7.setFont(font2)
        self.song7.setStyleSheet(u"background-color:yellow")
        self.song8 = QLabel(self.centralwidget)
        self.song8.setObjectName(u"song8")
        self.song8.setGeometry(QRect(340, 225, 171, 31))
        self.song8.setFont(font2)
        self.song8.setStyleSheet(u"background-color:yellow")
        self.song9 = QLabel(self.centralwidget)
        self.song9.setObjectName(u"song9")
        self.song9.setGeometry(QRect(340, 270, 171, 31))
        self.song9.setFont(font2)
        self.song9.setStyleSheet(u"background-color:yellow")
        self.song10 = QLabel(self.centralwidget)
        self.song10.setObjectName(u"song10")
        self.song10.setGeometry(QRect(340, 312, 171, 31))
        self.song10.setFont(font2)
        self.song10.setStyleSheet(u"background-color:yellow")
        self.song11 = QLabel(self.centralwidget)
        self.song11.setObjectName(u"song11")
        self.song11.setGeometry(QRect(340, 360, 171, 31))
        self.song11.setFont(font2)
        self.song11.setStyleSheet(u"background-color:yellow")
        self.song13 = QLabel(self.centralwidget)
        self.song13.setObjectName(u"song13")
        self.song13.setGeometry(QRect(710, 190, 161, 31))
        self.song13.setFont(font2)
        self.song13.setStyleSheet(u"background-color:yellow")
        self.song14 = QLabel(self.centralwidget)
        self.song14.setObjectName(u"song14")
        self.song14.setGeometry(QRect(710, 230, 161, 31))
        self.song14.setFont(font2)
        self.song14.setStyleSheet(u"background-color:yellow")
        self.song23 = QLabel(self.centralwidget)
        self.song23.setObjectName(u"song23")
        self.song23.setGeometry(QRect(880, 360, 151, 31))
        self.song23.setFont(font2)
        self.song23.setStyleSheet(u"background-color:yellow")
        self.song16 = QLabel(self.centralwidget)
        self.song16.setObjectName(u"song16")
        self.song16.setGeometry(QRect(712, 316, 161, 31))
        self.song16.setFont(font2)
        self.song16.setStyleSheet(u"background-color:yellow")
        self.song20 = QLabel(self.centralwidget)
        self.song20.setObjectName(u"song20")
        self.song20.setGeometry(QRect(880, 233, 151, 31))
        self.song20.setFont(font2)
        self.song20.setStyleSheet(u"background-color:yellow")
        self.song19 = QLabel(self.centralwidget)
        self.song19.setObjectName(u"song19")
        self.song19.setGeometry(QRect(880, 189, 151, 31))
        self.song19.setFont(font2)
        self.song19.setStyleSheet(u"background-color:yellow")
        self.song12 = QLabel(self.centralwidget)
        self.song12.setObjectName(u"song12")
        self.song12.setGeometry(QRect(710, 143, 161, 31))
        self.song12.setFont(font2)
        self.song12.setStyleSheet(u"background-color:yellow")
        self.song21 = QLabel(self.centralwidget)
        self.song21.setObjectName(u"song21")
        self.song21.setGeometry(QRect(880, 274, 151, 31))
        self.song21.setFont(font2)
        self.song21.setStyleSheet(u"background-color:yellow")
        self.song22 = QLabel(self.centralwidget)
        self.song22.setObjectName(u"song22")
        self.song22.setGeometry(QRect(880, 317, 151, 31))
        self.song22.setFont(font2)
        self.song22.setStyleSheet(u"background-color:yellow")
        self.song15 = QLabel(self.centralwidget)
        self.song15.setObjectName(u"song15")
        self.song15.setGeometry(QRect(712, 274, 161, 31))
        self.song15.setFont(font2)
        self.song15.setStyleSheet(u"background-color:yellow")
        self.song17 = QLabel(self.centralwidget)
        self.song17.setObjectName(u"song17")
        self.song17.setGeometry(QRect(710, 360, 161, 31))
        self.song17.setFont(font2)
        self.song17.setStyleSheet(u"background-color:yellow")
        self.song18 = QLabel(self.centralwidget)
        self.song18.setObjectName(u"song18")
        self.song18.setGeometry(QRect(878, 146, 151, 31))
        self.song18.setFont(font2)
        self.song18.setStyleSheet(u"background-color:yellow")
        self.buttons = QFrame(self.centralwidget)
        self.buttons.setObjectName(u"buttons")
        self.buttons.setGeometry(QRect(570, 110, 91, 281))
        self.buttons.setStyleSheet(u"background:transparent")
        self.buttons.setFrameShape(QFrame.Shape.StyledPanel)
        self.buttons.setFrameShadow(QFrame.Shadow.Raised)
        self.buttonforward = QPushButton(self.buttons)
        self.buttonforward.setObjectName(u"buttonforward")
        self.buttonforward.setGeometry(QRect(54, 247, 30, 30))
        font3 = QFont()
        font3.setFamilies([u"Love Craft"])
        self.buttonforward.setFont(font3)
        self.buttonforward.setAutoFillBackground(False)
        self.buttonforward.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"border-radius: 15px;")
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.GoNext))
        self.buttonforward.setIcon(icon)
        self.buttonbackward = QPushButton(self.buttons)
        self.buttonbackward.setObjectName(u"buttonbackward")
        self.buttonbackward.setGeometry(QRect(-1, 248, 30, 30))
        self.buttonbackward.setFont(font3)
        self.buttonbackward.setAutoFillBackground(False)
        self.buttonbackward.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"border-radius: 15px;")
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.GoPrevious))
        self.buttonbackward.setIcon(icon1)
        self.button5 = QPushButton(self.buttons)
        self.button5.setObjectName(u"button5")
        self.button5.setGeometry(QRect(0, 197, 30, 30))
        self.button5.setFont(font3)
        self.button5.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"border-radius: 15px;")
        self.button0 = QPushButton(self.buttons)
        self.button0.setObjectName(u"button0")
        self.button0.setGeometry(QRect(54, 197, 30, 30))
        self.button0.setFont(font3)
        self.button0.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"border-radius: 15px;")
        self.buttoin4 = QPushButton(self.buttons)
        self.buttoin4.setObjectName(u"buttoin4")
        self.buttoin4.setGeometry(QRect(1, 149, 30, 30))
        self.buttoin4.setFont(font3)
        self.buttoin4.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"border-radius: 15px;")
        self.button9 = QPushButton(self.buttons)
        self.button9.setObjectName(u"button9")
        self.button9.setGeometry(QRect(54, 149, 30, 30))
        self.button9.setFont(font3)
        self.button9.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"border-radius: 15px;")
        self.button3 = QPushButton(self.buttons)
        self.button3.setObjectName(u"button3")
        self.button3.setGeometry(QRect(1, 101, 30, 30))
        self.button3.setFont(font3)
        self.button3.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"border-radius: 15px;")
        self.button8 = QPushButton(self.buttons)
        self.button8.setObjectName(u"button8")
        self.button8.setGeometry(QRect(54, 101, 30, 30))
        self.button8.setFont(font3)
        self.button8.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"border-radius: 15px;")
        self.button2 = QPushButton(self.buttons)
        self.button2.setObjectName(u"button2")
        self.button2.setGeometry(QRect(1, 50, 30, 30))
        self.button2.setFont(font3)
        self.button2.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"border-radius: 15px;")
        self.button1 = QPushButton(self.buttons)
        self.button1.setObjectName(u"button1")
        self.button1.setGeometry(QRect(2, 2, 30, 30))
        self.button1.setFont(font3)
        self.button1.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"border-radius: 15px;")
        self.button1.setFlat(False)
        self.button6 = QPushButton(self.buttons)
        self.button6.setObjectName(u"button6")
        self.button6.setGeometry(QRect(55, 3, 30, 30))
        self.button6.setFont(font3)
        self.button6.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"border-radius: 15px;")
        self.button7 = QPushButton(self.buttons)
        self.button7.setObjectName(u"button7")
        self.button7.setGeometry(QRect(55, 52, 30, 30))
        self.button7.setFont(font3)
        self.button7.setStyleSheet(u"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0));\n"
"border-radius: 15px;")
        MainWindow.setCentralWidget(self.centralwidget)
        self.frontage.raise_()
        self.buttons.raise_()
        self.song0.raise_()
        self.song1.raise_()
        self.song2.raise_()
        self.song3.raise_()
        self.song4.raise_()
        self.song5.raise_()
        self.song6.raise_()
        self.song7.raise_()
        self.song8.raise_()
        self.song9.raise_()
        self.song10.raise_()
        self.song11.raise_()
        self.song13.raise_()
        self.song14.raise_()
        self.song23.raise_()
        self.song16.raise_()
        self.song20.raise_()
        self.song19.raise_()
        self.song12.raise_()
        self.song21.raise_()
        self.song22.raise_()
        self.song15.raise_()
        self.song17.raise_()
        self.song18.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1127, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.frontage.setText("")
        self.song0.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song1.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song2.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song3.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song4.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song5.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song6.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song7.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song8.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song9.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song10.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song11.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song13.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song14.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song23.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song16.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song20.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song19.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song12.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song21.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song22.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song15.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song17.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song18.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.buttonforward.setText("")
        self.buttonbackward.setText("")
        self.button5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.button0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.buttoin4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.button9.setText(QCoreApplication.translate("MainWindow", u"9", None))
        self.button3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.button8.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.button2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.button1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.button6.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.button7.setText(QCoreApplication.translate("MainWindow", u"7", None))
    # retranslateUi

