# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'app.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QLabel,
    QMainWindow, QPushButton, QScrollArea, QSizePolicy,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1249, 518)
        font = QFont()
        font.setFamilies([u"The Juke Box"])
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setStyleSheet(u"background-color: rgb(255, 180, 0);")
        self.buttons = QFrame(self.centralwidget)
        self.buttons.setObjectName(u"buttons")
        self.buttons.setGeometry(QRect(580, 110, 0, 0))
        self.buttons.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.buttons.setFrameShape(QFrame.Shape.StyledPanel)
        self.buttons.setFrameShadow(QFrame.Shadow.Raised)
        self.buttonforward = QPushButton(self.buttons)
        self.buttonforward.setObjectName(u"buttonforward")
        self.buttonforward.setGeometry(QRect(54, 247, 30, 30))
        font1 = QFont()
        font1.setFamilies([u"Love Craft"])
        self.buttonforward.setFont(font1)
        self.buttonforward.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.buttonforward.setAutoFillBackground(False)
        self.buttonforward.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.GoNext))
        self.buttonforward.setIcon(icon)
        self.buttonbackward = QPushButton(self.buttons)
        self.buttonbackward.setObjectName(u"buttonbackward")
        self.buttonbackward.setGeometry(QRect(-1, 248, 30, 30))
        self.buttonbackward.setFont(font1)
        self.buttonbackward.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.buttonbackward.setAutoFillBackground(False)
        self.buttonbackward.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.GoPrevious))
        self.buttonbackward.setIcon(icon1)
        self.button5 = QPushButton(self.buttons)
        self.button5.setObjectName(u"button5")
        self.button5.setGeometry(QRect(0, 197, 30, 30))
        self.button5.setFont(font1)
        self.button5.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.button5.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.button0 = QPushButton(self.buttons)
        self.button0.setObjectName(u"button0")
        self.button0.setGeometry(QRect(54, 197, 30, 30))
        self.button0.setFont(font1)
        self.button0.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.button0.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.button4 = QPushButton(self.buttons)
        self.button4.setObjectName(u"button4")
        self.button4.setGeometry(QRect(1, 149, 30, 30))
        self.button4.setFont(font1)
        self.button4.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.button4.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.button9 = QPushButton(self.buttons)
        self.button9.setObjectName(u"button9")
        self.button9.setGeometry(QRect(54, 149, 30, 30))
        self.button9.setFont(font1)
        self.button9.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.button9.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.button3 = QPushButton(self.buttons)
        self.button3.setObjectName(u"button3")
        self.button3.setGeometry(QRect(1, 101, 30, 30))
        self.button3.setFont(font1)
        self.button3.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.button3.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.button8 = QPushButton(self.buttons)
        self.button8.setObjectName(u"button8")
        self.button8.setGeometry(QRect(54, 101, 30, 30))
        self.button8.setFont(font1)
        self.button8.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.button8.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.button2 = QPushButton(self.buttons)
        self.button2.setObjectName(u"button2")
        self.button2.setGeometry(QRect(1, 50, 30, 30))
        self.button2.setFont(font1)
        self.button2.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.button2.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.button1 = QPushButton(self.buttons)
        self.button1.setObjectName(u"button1")
        self.button1.setGeometry(QRect(2, 2, 30, 30))
        self.button1.setFont(font1)
        self.button1.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.button1.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.button1.setFlat(False)
        self.button6 = QPushButton(self.buttons)
        self.button6.setObjectName(u"button6")
        self.button6.setGeometry(QRect(55, 3, 30, 30))
        self.button6.setFont(font1)
        self.button6.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.button6.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.button7 = QPushButton(self.buttons)
        self.button7.setObjectName(u"button7")
        self.button7.setGeometry(QRect(55, 52, 30, 30))
        self.button7.setFont(font1)
        self.button7.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.button7.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(50, 0, 263, 66))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.scrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 263, 45))
        self.horizontalLayout = QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.song0 = QLabel(self.scrollAreaWidgetContents)
        self.song0.setObjectName(u"song0")
        font2 = QFont()
        font2.setFamilies([u"Arcane Nine"])
        font2.setPointSize(18)
        self.song0.setFont(font2)
        self.song0.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.song0.setWordWrap(False)

        self.horizontalLayout.addWidget(self.song0)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_12 = QScrollArea(self.centralwidget)
        self.scrollArea_12.setObjectName(u"scrollArea_12")
        self.scrollArea_12.setGeometry(QRect(387, 0, 250, 66))
        sizePolicy.setHeightForWidth(self.scrollArea_12.sizePolicy().hasHeightForWidth())
        self.scrollArea_12.setSizePolicy(sizePolicy)
        self.scrollArea_12.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.scrollArea_12.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_12.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_12.setWidgetResizable(True)
        self.scrollAreaWidgetContents_27 = QWidget()
        self.scrollAreaWidgetContents_27.setObjectName(u"scrollAreaWidgetContents_27")
        self.scrollAreaWidgetContents_27.setGeometry(QRect(0, 0, 250, 45))
        self.horizontalLayout_26 = QHBoxLayout(self.scrollAreaWidgetContents_27)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName(u"horizontalLayout_26")
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.song6 = QLabel(self.scrollAreaWidgetContents_27)
        self.song6.setObjectName(u"song6")
        self.song6.setFont(font2)
        self.song6.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")

        self.horizontalLayout_26.addWidget(self.song6)

        self.scrollArea_12.setWidget(self.scrollAreaWidgetContents_27)
        self.num = QLabel(self.centralwidget)
        self.num.setObjectName(u"num")
        self.num.setGeometry(QRect(347, 0, 40, 51))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.num.sizePolicy().hasHeightForWidth())
        self.num.setSizePolicy(sizePolicy1)
        self.num.setFont(font2)
        self.num.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.num_3 = QLabel(self.centralwidget)
        self.num_3.setObjectName(u"num_3")
        self.num_3.setGeometry(QRect(10, 0, 40, 51))
        sizePolicy1.setHeightForWidth(self.num_3.sizePolicy().hasHeightForWidth())
        self.num_3.setSizePolicy(sizePolicy1)
        self.num_3.setFont(font2)
        self.num_3.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.num_2 = QLabel(self.centralwidget)
        self.num_2.setObjectName(u"num_2")
        self.num_2.setGeometry(QRect(347, 85, 40, 51))
        sizePolicy1.setHeightForWidth(self.num_2.sizePolicy().hasHeightForWidth())
        self.num_2.setSizePolicy(sizePolicy1)
        self.num_2.setFont(font2)
        self.num_2.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.scrollArea_25 = QScrollArea(self.centralwidget)
        self.scrollArea_25.setObjectName(u"scrollArea_25")
        self.scrollArea_25.setGeometry(QRect(387, 85, 250, 66))
        sizePolicy.setHeightForWidth(self.scrollArea_25.sizePolicy().hasHeightForWidth())
        self.scrollArea_25.setSizePolicy(sizePolicy)
        self.scrollArea_25.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.scrollArea_25.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_25.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_25.setWidgetResizable(True)
        self.scrollAreaWidgetContents_42 = QWidget()
        self.scrollAreaWidgetContents_42.setObjectName(u"scrollAreaWidgetContents_42")
        self.scrollAreaWidgetContents_42.setGeometry(QRect(0, 0, 250, 45))
        self.horizontalLayout_41 = QHBoxLayout(self.scrollAreaWidgetContents_42)
        self.horizontalLayout_41.setSpacing(0)
        self.horizontalLayout_41.setObjectName(u"horizontalLayout_41")
        self.horizontalLayout_41.setContentsMargins(0, 0, 0, 0)
        self.song7 = QLabel(self.scrollAreaWidgetContents_42)
        self.song7.setObjectName(u"song7")
        self.song7.setFont(font2)
        self.song7.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")

        self.horizontalLayout_41.addWidget(self.song7)

        self.scrollArea_25.setWidget(self.scrollAreaWidgetContents_42)
        self.num_4 = QLabel(self.centralwidget)
        self.num_4.setObjectName(u"num_4")
        self.num_4.setGeometry(QRect(10, 85, 40, 51))
        sizePolicy1.setHeightForWidth(self.num_4.sizePolicy().hasHeightForWidth())
        self.num_4.setSizePolicy(sizePolicy1)
        self.num_4.setFont(font2)
        self.num_4.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.scrollArea_2 = QScrollArea(self.centralwidget)
        self.scrollArea_2.setObjectName(u"scrollArea_2")
        self.scrollArea_2.setGeometry(QRect(50, 85, 263, 66))
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.scrollArea_2.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_2.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollAreaWidgetContents_4 = QWidget()
        self.scrollAreaWidgetContents_4.setObjectName(u"scrollAreaWidgetContents_4")
        self.scrollAreaWidgetContents_4.setGeometry(QRect(0, 0, 263, 45))
        self.horizontalLayout_4 = QHBoxLayout(self.scrollAreaWidgetContents_4)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.song1 = QLabel(self.scrollAreaWidgetContents_4)
        self.song1.setObjectName(u"song1")
        self.song1.setFont(font2)
        self.song1.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.song1.setWordWrap(False)

        self.horizontalLayout_4.addWidget(self.song1)

        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_4)
        self.num_5 = QLabel(self.centralwidget)
        self.num_5.setObjectName(u"num_5")
        self.num_5.setGeometry(QRect(347, 170, 40, 51))
        sizePolicy1.setHeightForWidth(self.num_5.sizePolicy().hasHeightForWidth())
        self.num_5.setSizePolicy(sizePolicy1)
        self.num_5.setFont(font2)
        self.num_5.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.scrollArea_26 = QScrollArea(self.centralwidget)
        self.scrollArea_26.setObjectName(u"scrollArea_26")
        self.scrollArea_26.setGeometry(QRect(387, 170, 250, 66))
        sizePolicy.setHeightForWidth(self.scrollArea_26.sizePolicy().hasHeightForWidth())
        self.scrollArea_26.setSizePolicy(sizePolicy)
        self.scrollArea_26.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.scrollArea_26.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_26.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_26.setWidgetResizable(True)
        self.scrollAreaWidgetContents_43 = QWidget()
        self.scrollAreaWidgetContents_43.setObjectName(u"scrollAreaWidgetContents_43")
        self.scrollAreaWidgetContents_43.setGeometry(QRect(0, 0, 250, 45))
        self.horizontalLayout_42 = QHBoxLayout(self.scrollAreaWidgetContents_43)
        self.horizontalLayout_42.setSpacing(0)
        self.horizontalLayout_42.setObjectName(u"horizontalLayout_42")
        self.horizontalLayout_42.setContentsMargins(0, 0, 0, 0)
        self.song8 = QLabel(self.scrollAreaWidgetContents_43)
        self.song8.setObjectName(u"song8")
        self.song8.setFont(font2)
        self.song8.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")

        self.horizontalLayout_42.addWidget(self.song8)

        self.scrollArea_26.setWidget(self.scrollAreaWidgetContents_43)
        self.num_6 = QLabel(self.centralwidget)
        self.num_6.setObjectName(u"num_6")
        self.num_6.setGeometry(QRect(10, 170, 40, 51))
        sizePolicy1.setHeightForWidth(self.num_6.sizePolicy().hasHeightForWidth())
        self.num_6.setSizePolicy(sizePolicy1)
        self.num_6.setFont(font2)
        self.num_6.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.scrollArea_3 = QScrollArea(self.centralwidget)
        self.scrollArea_3.setObjectName(u"scrollArea_3")
        self.scrollArea_3.setGeometry(QRect(50, 170, 263, 66))
        sizePolicy.setHeightForWidth(self.scrollArea_3.sizePolicy().hasHeightForWidth())
        self.scrollArea_3.setSizePolicy(sizePolicy)
        self.scrollArea_3.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.scrollArea_3.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_3.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollAreaWidgetContents_5 = QWidget()
        self.scrollAreaWidgetContents_5.setObjectName(u"scrollAreaWidgetContents_5")
        self.scrollAreaWidgetContents_5.setGeometry(QRect(0, 0, 263, 45))
        self.horizontalLayout_5 = QHBoxLayout(self.scrollAreaWidgetContents_5)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.song2 = QLabel(self.scrollAreaWidgetContents_5)
        self.song2.setObjectName(u"song2")
        self.song2.setFont(font2)
        self.song2.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.song2.setWordWrap(False)

        self.horizontalLayout_5.addWidget(self.song2)

        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_5)
        self.num_7 = QLabel(self.centralwidget)
        self.num_7.setObjectName(u"num_7")
        self.num_7.setGeometry(QRect(347, 255, 40, 51))
        sizePolicy1.setHeightForWidth(self.num_7.sizePolicy().hasHeightForWidth())
        self.num_7.setSizePolicy(sizePolicy1)
        self.num_7.setFont(font2)
        self.num_7.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.scrollArea_27 = QScrollArea(self.centralwidget)
        self.scrollArea_27.setObjectName(u"scrollArea_27")
        self.scrollArea_27.setGeometry(QRect(387, 255, 250, 66))
        sizePolicy.setHeightForWidth(self.scrollArea_27.sizePolicy().hasHeightForWidth())
        self.scrollArea_27.setSizePolicy(sizePolicy)
        self.scrollArea_27.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.scrollArea_27.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_27.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_27.setWidgetResizable(True)
        self.scrollAreaWidgetContents_44 = QWidget()
        self.scrollAreaWidgetContents_44.setObjectName(u"scrollAreaWidgetContents_44")
        self.scrollAreaWidgetContents_44.setGeometry(QRect(0, 0, 250, 45))
        self.horizontalLayout_43 = QHBoxLayout(self.scrollAreaWidgetContents_44)
        self.horizontalLayout_43.setSpacing(0)
        self.horizontalLayout_43.setObjectName(u"horizontalLayout_43")
        self.horizontalLayout_43.setContentsMargins(0, 0, 0, 0)
        self.song9 = QLabel(self.scrollAreaWidgetContents_44)
        self.song9.setObjectName(u"song9")
        self.song9.setFont(font2)
        self.song9.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")

        self.horizontalLayout_43.addWidget(self.song9)

        self.scrollArea_27.setWidget(self.scrollAreaWidgetContents_44)
        self.num_8 = QLabel(self.centralwidget)
        self.num_8.setObjectName(u"num_8")
        self.num_8.setGeometry(QRect(10, 255, 40, 51))
        sizePolicy1.setHeightForWidth(self.num_8.sizePolicy().hasHeightForWidth())
        self.num_8.setSizePolicy(sizePolicy1)
        self.num_8.setFont(font2)
        self.num_8.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.scrollArea_4 = QScrollArea(self.centralwidget)
        self.scrollArea_4.setObjectName(u"scrollArea_4")
        self.scrollArea_4.setGeometry(QRect(50, 255, 263, 66))
        sizePolicy.setHeightForWidth(self.scrollArea_4.sizePolicy().hasHeightForWidth())
        self.scrollArea_4.setSizePolicy(sizePolicy)
        self.scrollArea_4.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.scrollArea_4.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_4.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollAreaWidgetContents_6 = QWidget()
        self.scrollAreaWidgetContents_6.setObjectName(u"scrollAreaWidgetContents_6")
        self.scrollAreaWidgetContents_6.setGeometry(QRect(0, 0, 263, 45))
        self.horizontalLayout_6 = QHBoxLayout(self.scrollAreaWidgetContents_6)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.song3 = QLabel(self.scrollAreaWidgetContents_6)
        self.song3.setObjectName(u"song3")
        self.song3.setFont(font2)
        self.song3.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.song3.setWordWrap(False)

        self.horizontalLayout_6.addWidget(self.song3)

        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_6)
        self.num_9 = QLabel(self.centralwidget)
        self.num_9.setObjectName(u"num_9")
        self.num_9.setGeometry(QRect(347, 340, 40, 51))
        sizePolicy1.setHeightForWidth(self.num_9.sizePolicy().hasHeightForWidth())
        self.num_9.setSizePolicy(sizePolicy1)
        self.num_9.setFont(font2)
        self.num_9.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.scrollArea_28 = QScrollArea(self.centralwidget)
        self.scrollArea_28.setObjectName(u"scrollArea_28")
        self.scrollArea_28.setGeometry(QRect(387, 340, 250, 66))
        sizePolicy.setHeightForWidth(self.scrollArea_28.sizePolicy().hasHeightForWidth())
        self.scrollArea_28.setSizePolicy(sizePolicy)
        self.scrollArea_28.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.scrollArea_28.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_28.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_28.setWidgetResizable(True)
        self.scrollAreaWidgetContents_45 = QWidget()
        self.scrollAreaWidgetContents_45.setObjectName(u"scrollAreaWidgetContents_45")
        self.scrollAreaWidgetContents_45.setGeometry(QRect(0, 0, 250, 45))
        self.horizontalLayout_44 = QHBoxLayout(self.scrollAreaWidgetContents_45)
        self.horizontalLayout_44.setSpacing(0)
        self.horizontalLayout_44.setObjectName(u"horizontalLayout_44")
        self.horizontalLayout_44.setContentsMargins(0, 0, 0, 0)
        self.song10 = QLabel(self.scrollAreaWidgetContents_45)
        self.song10.setObjectName(u"song10")
        self.song10.setFont(font2)
        self.song10.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")

        self.horizontalLayout_44.addWidget(self.song10)

        self.scrollArea_28.setWidget(self.scrollAreaWidgetContents_45)
        self.num_10 = QLabel(self.centralwidget)
        self.num_10.setObjectName(u"num_10")
        self.num_10.setGeometry(QRect(10, 340, 40, 51))
        sizePolicy1.setHeightForWidth(self.num_10.sizePolicy().hasHeightForWidth())
        self.num_10.setSizePolicy(sizePolicy1)
        self.num_10.setFont(font2)
        self.num_10.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.scrollArea_5 = QScrollArea(self.centralwidget)
        self.scrollArea_5.setObjectName(u"scrollArea_5")
        self.scrollArea_5.setGeometry(QRect(50, 340, 263, 66))
        sizePolicy.setHeightForWidth(self.scrollArea_5.sizePolicy().hasHeightForWidth())
        self.scrollArea_5.setSizePolicy(sizePolicy)
        self.scrollArea_5.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.scrollArea_5.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_5.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollAreaWidgetContents_7 = QWidget()
        self.scrollAreaWidgetContents_7.setObjectName(u"scrollAreaWidgetContents_7")
        self.scrollAreaWidgetContents_7.setGeometry(QRect(0, 0, 263, 45))
        self.horizontalLayout_7 = QHBoxLayout(self.scrollAreaWidgetContents_7)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.song4 = QLabel(self.scrollAreaWidgetContents_7)
        self.song4.setObjectName(u"song4")
        self.song4.setFont(font2)
        self.song4.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.song4.setWordWrap(False)

        self.horizontalLayout_7.addWidget(self.song4)

        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_7)
        self.scrollArea_29 = QScrollArea(self.centralwidget)
        self.scrollArea_29.setObjectName(u"scrollArea_29")
        self.scrollArea_29.setGeometry(QRect(390, 425, 250, 66))
        sizePolicy.setHeightForWidth(self.scrollArea_29.sizePolicy().hasHeightForWidth())
        self.scrollArea_29.setSizePolicy(sizePolicy)
        self.scrollArea_29.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.scrollArea_29.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_29.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_29.setWidgetResizable(True)
        self.scrollAreaWidgetContents_41 = QWidget()
        self.scrollAreaWidgetContents_41.setObjectName(u"scrollAreaWidgetContents_41")
        self.scrollAreaWidgetContents_41.setGeometry(QRect(0, 0, 250, 45))
        self.horizontalLayout_40 = QHBoxLayout(self.scrollAreaWidgetContents_41)
        self.horizontalLayout_40.setSpacing(0)
        self.horizontalLayout_40.setObjectName(u"horizontalLayout_40")
        self.horizontalLayout_40.setContentsMargins(0, 0, 0, 0)
        self.song11 = QLabel(self.scrollAreaWidgetContents_41)
        self.song11.setObjectName(u"song11")
        self.song11.setFont(font2)
        self.song11.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")

        self.horizontalLayout_40.addWidget(self.song11)

        self.scrollArea_29.setWidget(self.scrollAreaWidgetContents_41)
        self.num_11 = QLabel(self.centralwidget)
        self.num_11.setObjectName(u"num_11")
        self.num_11.setGeometry(QRect(10, 425, 40, 51))
        sizePolicy1.setHeightForWidth(self.num_11.sizePolicy().hasHeightForWidth())
        self.num_11.setSizePolicy(sizePolicy1)
        self.num_11.setFont(font2)
        self.num_11.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.scrollArea_6 = QScrollArea(self.centralwidget)
        self.scrollArea_6.setObjectName(u"scrollArea_6")
        self.scrollArea_6.setGeometry(QRect(50, 425, 263, 66))
        sizePolicy.setHeightForWidth(self.scrollArea_6.sizePolicy().hasHeightForWidth())
        self.scrollArea_6.setSizePolicy(sizePolicy)
        self.scrollArea_6.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.scrollArea_6.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_6.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollAreaWidgetContents_3 = QWidget()
        self.scrollAreaWidgetContents_3.setObjectName(u"scrollAreaWidgetContents_3")
        self.scrollAreaWidgetContents_3.setGeometry(QRect(0, 0, 263, 45))
        self.horizontalLayout_3 = QHBoxLayout(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.song5 = QLabel(self.scrollAreaWidgetContents_3)
        self.song5.setObjectName(u"song5")
        self.song5.setFont(font2)
        self.song5.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.song5.setWordWrap(False)

        self.horizontalLayout_3.addWidget(self.song5)

        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_3)
        self.num_12 = QLabel(self.centralwidget)
        self.num_12.setObjectName(u"num_12")
        self.num_12.setGeometry(QRect(347, 425, 40, 51))
        sizePolicy1.setHeightForWidth(self.num_12.sizePolicy().hasHeightForWidth())
        self.num_12.setSizePolicy(sizePolicy1)
        self.num_12.setFont(font2)
        self.num_12.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        self.num_13 = QLabel(self.centralwidget)
        self.num_13.setObjectName(u"num_13")
        self.num_13.setGeometry(QRect(650, 255, 40, 51))
        sizePolicy1.setHeightForWidth(self.num_13.sizePolicy().hasHeightForWidth())
        self.num_13.setSizePolicy(sizePolicy1)
        self.num_13.setFont(font2)
        self.num_13.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.num_14 = QLabel(self.centralwidget)
        self.num_14.setObjectName(u"num_14")
        self.num_14.setGeometry(QRect(650, 170, 40, 51))
        sizePolicy1.setHeightForWidth(self.num_14.sizePolicy().hasHeightForWidth())
        self.num_14.setSizePolicy(sizePolicy1)
        self.num_14.setFont(font2)
        self.num_14.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.scrollArea_7 = QScrollArea(self.centralwidget)
        self.scrollArea_7.setObjectName(u"scrollArea_7")
        self.scrollArea_7.setGeometry(QRect(690, 170, 263, 66))
        sizePolicy.setHeightForWidth(self.scrollArea_7.sizePolicy().hasHeightForWidth())
        self.scrollArea_7.setSizePolicy(sizePolicy)
        self.scrollArea_7.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.scrollArea_7.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_7.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollAreaWidgetContents_14 = QWidget()
        self.scrollAreaWidgetContents_14.setObjectName(u"scrollAreaWidgetContents_14")
        self.scrollAreaWidgetContents_14.setGeometry(QRect(0, 0, 263, 45))
        self.horizontalLayout_14 = QHBoxLayout(self.scrollAreaWidgetContents_14)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName(u"horizontalLayout_14")
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.song14 = QLabel(self.scrollAreaWidgetContents_14)
        self.song14.setObjectName(u"song14")
        self.song14.setFont(font2)
        self.song14.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.song14.setWordWrap(False)

        self.horizontalLayout_14.addWidget(self.song14)

        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_14)
        self.scrollArea_30 = QScrollArea(self.centralwidget)
        self.scrollArea_30.setObjectName(u"scrollArea_30")
        self.scrollArea_30.setGeometry(QRect(1027, 255, 263, 66))
        sizePolicy.setHeightForWidth(self.scrollArea_30.sizePolicy().hasHeightForWidth())
        self.scrollArea_30.setSizePolicy(sizePolicy)
        self.scrollArea_30.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.scrollArea_30.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_30.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_30.setWidgetResizable(True)
        self.scrollAreaWidgetContents_51 = QWidget()
        self.scrollAreaWidgetContents_51.setObjectName(u"scrollAreaWidgetContents_51")
        self.scrollAreaWidgetContents_51.setGeometry(QRect(0, 0, 263, 45))
        self.horizontalLayout_50 = QHBoxLayout(self.scrollAreaWidgetContents_51)
        self.horizontalLayout_50.setSpacing(0)
        self.horizontalLayout_50.setObjectName(u"horizontalLayout_50")
        self.horizontalLayout_50.setContentsMargins(0, 0, 0, 0)
        self.song21 = QLabel(self.scrollAreaWidgetContents_51)
        self.song21.setObjectName(u"song21")
        self.song21.setFont(font2)
        self.song21.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")

        self.horizontalLayout_50.addWidget(self.song21)

        self.scrollArea_30.setWidget(self.scrollAreaWidgetContents_51)
        self.scrollArea_8 = QScrollArea(self.centralwidget)
        self.scrollArea_8.setObjectName(u"scrollArea_8")
        self.scrollArea_8.setGeometry(QRect(690, 425, 263, 66))
        sizePolicy.setHeightForWidth(self.scrollArea_8.sizePolicy().hasHeightForWidth())
        self.scrollArea_8.setSizePolicy(sizePolicy)
        self.scrollArea_8.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.scrollArea_8.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_8.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_8.setWidgetResizable(True)
        self.scrollAreaWidgetContents_15 = QWidget()
        self.scrollAreaWidgetContents_15.setObjectName(u"scrollAreaWidgetContents_15")
        self.scrollAreaWidgetContents_15.setGeometry(QRect(0, 0, 263, 45))
        self.horizontalLayout_15 = QHBoxLayout(self.scrollAreaWidgetContents_15)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName(u"horizontalLayout_15")
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.song17 = QLabel(self.scrollAreaWidgetContents_15)
        self.song17.setObjectName(u"song17")
        self.song17.setFont(font2)
        self.song17.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.song17.setWordWrap(False)

        self.horizontalLayout_15.addWidget(self.song17)

        self.scrollArea_8.setWidget(self.scrollAreaWidgetContents_15)
        self.scrollArea_13 = QScrollArea(self.centralwidget)
        self.scrollArea_13.setObjectName(u"scrollArea_13")
        self.scrollArea_13.setGeometry(QRect(1027, 0, 263, 66))
        sizePolicy.setHeightForWidth(self.scrollArea_13.sizePolicy().hasHeightForWidth())
        self.scrollArea_13.setSizePolicy(sizePolicy)
        self.scrollArea_13.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.scrollArea_13.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_13.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_13.setWidgetResizable(True)
        self.scrollAreaWidgetContents_29 = QWidget()
        self.scrollAreaWidgetContents_29.setObjectName(u"scrollAreaWidgetContents_29")
        self.scrollAreaWidgetContents_29.setGeometry(QRect(0, 0, 263, 45))
        self.horizontalLayout_28 = QHBoxLayout(self.scrollAreaWidgetContents_29)
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setObjectName(u"horizontalLayout_28")
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.song18 = QLabel(self.scrollAreaWidgetContents_29)
        self.song18.setObjectName(u"song18")
        self.song18.setFont(font2)
        self.song18.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")

        self.horizontalLayout_28.addWidget(self.song18)

        self.scrollArea_13.setWidget(self.scrollAreaWidgetContents_29)
        self.num_15 = QLabel(self.centralwidget)
        self.num_15.setObjectName(u"num_15")
        self.num_15.setGeometry(QRect(987, 170, 40, 51))
        sizePolicy1.setHeightForWidth(self.num_15.sizePolicy().hasHeightForWidth())
        self.num_15.setSizePolicy(sizePolicy1)
        self.num_15.setFont(font2)
        self.num_15.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.num_16 = QLabel(self.centralwidget)
        self.num_16.setObjectName(u"num_16")
        self.num_16.setGeometry(QRect(987, 425, 40, 51))
        sizePolicy1.setHeightForWidth(self.num_16.sizePolicy().hasHeightForWidth())
        self.num_16.setSizePolicy(sizePolicy1)
        self.num_16.setFont(font2)
        self.num_16.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.scrollArea_31 = QScrollArea(self.centralwidget)
        self.scrollArea_31.setObjectName(u"scrollArea_31")
        self.scrollArea_31.setGeometry(QRect(1027, 340, 263, 66))
        sizePolicy.setHeightForWidth(self.scrollArea_31.sizePolicy().hasHeightForWidth())
        self.scrollArea_31.setSizePolicy(sizePolicy)
        self.scrollArea_31.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.scrollArea_31.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_31.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_31.setWidgetResizable(True)
        self.scrollAreaWidgetContents_52 = QWidget()
        self.scrollAreaWidgetContents_52.setObjectName(u"scrollAreaWidgetContents_52")
        self.scrollAreaWidgetContents_52.setGeometry(QRect(0, 0, 263, 45))
        self.horizontalLayout_51 = QHBoxLayout(self.scrollAreaWidgetContents_52)
        self.horizontalLayout_51.setSpacing(0)
        self.horizontalLayout_51.setObjectName(u"horizontalLayout_51")
        self.horizontalLayout_51.setContentsMargins(0, 0, 0, 0)
        self.song22 = QLabel(self.scrollAreaWidgetContents_52)
        self.song22.setObjectName(u"song22")
        self.song22.setFont(font2)
        self.song22.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")

        self.horizontalLayout_51.addWidget(self.song22)

        self.scrollArea_31.setWidget(self.scrollAreaWidgetContents_52)
        self.num_17 = QLabel(self.centralwidget)
        self.num_17.setObjectName(u"num_17")
        self.num_17.setGeometry(QRect(650, 0, 40, 51))
        sizePolicy1.setHeightForWidth(self.num_17.sizePolicy().hasHeightForWidth())
        self.num_17.setSizePolicy(sizePolicy1)
        self.num_17.setFont(font2)
        self.num_17.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.num_18 = QLabel(self.centralwidget)
        self.num_18.setObjectName(u"num_18")
        self.num_18.setGeometry(QRect(650, 425, 40, 51))
        sizePolicy1.setHeightForWidth(self.num_18.sizePolicy().hasHeightForWidth())
        self.num_18.setSizePolicy(sizePolicy1)
        self.num_18.setFont(font2)
        self.num_18.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.num_19 = QLabel(self.centralwidget)
        self.num_19.setObjectName(u"num_19")
        self.num_19.setGeometry(QRect(987, 340, 40, 51))
        sizePolicy1.setHeightForWidth(self.num_19.sizePolicy().hasHeightForWidth())
        self.num_19.setSizePolicy(sizePolicy1)
        self.num_19.setFont(font2)
        self.num_19.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.num_20 = QLabel(self.centralwidget)
        self.num_20.setObjectName(u"num_20")
        self.num_20.setGeometry(QRect(650, 340, 40, 51))
        sizePolicy1.setHeightForWidth(self.num_20.sizePolicy().hasHeightForWidth())
        self.num_20.setSizePolicy(sizePolicy1)
        self.num_20.setFont(font2)
        self.num_20.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.num_21 = QLabel(self.centralwidget)
        self.num_21.setObjectName(u"num_21")
        self.num_21.setGeometry(QRect(650, 85, 40, 51))
        sizePolicy1.setHeightForWidth(self.num_21.sizePolicy().hasHeightForWidth())
        self.num_21.setSizePolicy(sizePolicy1)
        self.num_21.setFont(font2)
        self.num_21.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.scrollArea_32 = QScrollArea(self.centralwidget)
        self.scrollArea_32.setObjectName(u"scrollArea_32")
        self.scrollArea_32.setGeometry(QRect(1027, 425, 263, 66))
        sizePolicy.setHeightForWidth(self.scrollArea_32.sizePolicy().hasHeightForWidth())
        self.scrollArea_32.setSizePolicy(sizePolicy)
        self.scrollArea_32.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.scrollArea_32.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_32.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_32.setWidgetResizable(True)
        self.scrollAreaWidgetContents_53 = QWidget()
        self.scrollAreaWidgetContents_53.setObjectName(u"scrollAreaWidgetContents_53")
        self.scrollAreaWidgetContents_53.setGeometry(QRect(0, 0, 263, 45))
        self.horizontalLayout_52 = QHBoxLayout(self.scrollAreaWidgetContents_53)
        self.horizontalLayout_52.setSpacing(0)
        self.horizontalLayout_52.setObjectName(u"horizontalLayout_52")
        self.horizontalLayout_52.setContentsMargins(0, 0, 0, 0)
        self.song23 = QLabel(self.scrollAreaWidgetContents_53)
        self.song23.setObjectName(u"song23")
        self.song23.setFont(font2)
        self.song23.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")

        self.horizontalLayout_52.addWidget(self.song23)

        self.scrollArea_32.setWidget(self.scrollAreaWidgetContents_53)
        self.scrollArea_33 = QScrollArea(self.centralwidget)
        self.scrollArea_33.setObjectName(u"scrollArea_33")
        self.scrollArea_33.setGeometry(QRect(1027, 85, 263, 66))
        sizePolicy.setHeightForWidth(self.scrollArea_33.sizePolicy().hasHeightForWidth())
        self.scrollArea_33.setSizePolicy(sizePolicy)
        self.scrollArea_33.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.scrollArea_33.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_33.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_33.setWidgetResizable(True)
        self.scrollAreaWidgetContents_54 = QWidget()
        self.scrollAreaWidgetContents_54.setObjectName(u"scrollAreaWidgetContents_54")
        self.scrollAreaWidgetContents_54.setGeometry(QRect(0, 0, 263, 45))
        self.horizontalLayout_53 = QHBoxLayout(self.scrollAreaWidgetContents_54)
        self.horizontalLayout_53.setSpacing(0)
        self.horizontalLayout_53.setObjectName(u"horizontalLayout_53")
        self.horizontalLayout_53.setContentsMargins(0, 0, 0, 0)
        self.song19 = QLabel(self.scrollAreaWidgetContents_54)
        self.song19.setObjectName(u"song19")
        self.song19.setFont(font2)
        self.song19.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")

        self.horizontalLayout_53.addWidget(self.song19)

        self.scrollArea_33.setWidget(self.scrollAreaWidgetContents_54)
        self.num_22 = QLabel(self.centralwidget)
        self.num_22.setObjectName(u"num_22")
        self.num_22.setGeometry(QRect(987, 255, 40, 51))
        sizePolicy1.setHeightForWidth(self.num_22.sizePolicy().hasHeightForWidth())
        self.num_22.setSizePolicy(sizePolicy1)
        self.num_22.setFont(font2)
        self.num_22.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.scrollArea_9 = QScrollArea(self.centralwidget)
        self.scrollArea_9.setObjectName(u"scrollArea_9")
        self.scrollArea_9.setGeometry(QRect(690, 0, 263, 66))
        sizePolicy.setHeightForWidth(self.scrollArea_9.sizePolicy().hasHeightForWidth())
        self.scrollArea_9.setSizePolicy(sizePolicy)
        self.scrollArea_9.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.scrollArea_9.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_9.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_9.setWidgetResizable(True)
        self.scrollAreaWidgetContents_16 = QWidget()
        self.scrollAreaWidgetContents_16.setObjectName(u"scrollAreaWidgetContents_16")
        self.scrollAreaWidgetContents_16.setGeometry(QRect(0, 0, 263, 45))
        self.horizontalLayout_16 = QHBoxLayout(self.scrollAreaWidgetContents_16)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName(u"horizontalLayout_16")
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.song12 = QLabel(self.scrollAreaWidgetContents_16)
        self.song12.setObjectName(u"song12")
        self.song12.setFont(font2)
        self.song12.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.song12.setWordWrap(False)

        self.horizontalLayout_16.addWidget(self.song12)

        self.scrollArea_9.setWidget(self.scrollAreaWidgetContents_16)
        self.scrollArea_10 = QScrollArea(self.centralwidget)
        self.scrollArea_10.setObjectName(u"scrollArea_10")
        self.scrollArea_10.setGeometry(QRect(690, 255, 263, 66))
        sizePolicy.setHeightForWidth(self.scrollArea_10.sizePolicy().hasHeightForWidth())
        self.scrollArea_10.setSizePolicy(sizePolicy)
        self.scrollArea_10.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.scrollArea_10.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_10.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_10.setWidgetResizable(True)
        self.scrollAreaWidgetContents_17 = QWidget()
        self.scrollAreaWidgetContents_17.setObjectName(u"scrollAreaWidgetContents_17")
        self.scrollAreaWidgetContents_17.setGeometry(QRect(0, 0, 263, 45))
        self.horizontalLayout_17 = QHBoxLayout(self.scrollAreaWidgetContents_17)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName(u"horizontalLayout_17")
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.song15 = QLabel(self.scrollAreaWidgetContents_17)
        self.song15.setObjectName(u"song15")
        self.song15.setFont(font2)
        self.song15.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.song15.setWordWrap(False)

        self.horizontalLayout_17.addWidget(self.song15)

        self.scrollArea_10.setWidget(self.scrollAreaWidgetContents_17)
        self.scrollArea_11 = QScrollArea(self.centralwidget)
        self.scrollArea_11.setObjectName(u"scrollArea_11")
        self.scrollArea_11.setGeometry(QRect(690, 340, 263, 66))
        sizePolicy.setHeightForWidth(self.scrollArea_11.sizePolicy().hasHeightForWidth())
        self.scrollArea_11.setSizePolicy(sizePolicy)
        self.scrollArea_11.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.scrollArea_11.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_11.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_11.setWidgetResizable(True)
        self.scrollAreaWidgetContents_18 = QWidget()
        self.scrollAreaWidgetContents_18.setObjectName(u"scrollAreaWidgetContents_18")
        self.scrollAreaWidgetContents_18.setGeometry(QRect(0, 0, 263, 45))
        self.horizontalLayout_18 = QHBoxLayout(self.scrollAreaWidgetContents_18)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName(u"horizontalLayout_18")
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.song16 = QLabel(self.scrollAreaWidgetContents_18)
        self.song16.setObjectName(u"song16")
        self.song16.setFont(font2)
        self.song16.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.song16.setWordWrap(False)

        self.horizontalLayout_18.addWidget(self.song16)

        self.scrollArea_11.setWidget(self.scrollAreaWidgetContents_18)
        self.num_23 = QLabel(self.centralwidget)
        self.num_23.setObjectName(u"num_23")
        self.num_23.setGeometry(QRect(987, 0, 40, 51))
        sizePolicy1.setHeightForWidth(self.num_23.sizePolicy().hasHeightForWidth())
        self.num_23.setSizePolicy(sizePolicy1)
        self.num_23.setFont(font2)
        self.num_23.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.num_24 = QLabel(self.centralwidget)
        self.num_24.setObjectName(u"num_24")
        self.num_24.setGeometry(QRect(987, 85, 40, 51))
        sizePolicy1.setHeightForWidth(self.num_24.sizePolicy().hasHeightForWidth())
        self.num_24.setSizePolicy(sizePolicy1)
        self.num_24.setFont(font2)
        self.num_24.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.scrollArea_34 = QScrollArea(self.centralwidget)
        self.scrollArea_34.setObjectName(u"scrollArea_34")
        self.scrollArea_34.setGeometry(QRect(1027, 170, 263, 66))
        sizePolicy.setHeightForWidth(self.scrollArea_34.sizePolicy().hasHeightForWidth())
        self.scrollArea_34.setSizePolicy(sizePolicy)
        self.scrollArea_34.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.scrollArea_34.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_34.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_34.setWidgetResizable(True)
        self.scrollAreaWidgetContents_55 = QWidget()
        self.scrollAreaWidgetContents_55.setObjectName(u"scrollAreaWidgetContents_55")
        self.scrollAreaWidgetContents_55.setGeometry(QRect(0, 0, 263, 45))
        self.horizontalLayout_54 = QHBoxLayout(self.scrollAreaWidgetContents_55)
        self.horizontalLayout_54.setSpacing(0)
        self.horizontalLayout_54.setObjectName(u"horizontalLayout_54")
        self.horizontalLayout_54.setContentsMargins(0, 0, 0, 0)
        self.song20 = QLabel(self.scrollAreaWidgetContents_55)
        self.song20.setObjectName(u"song20")
        self.song20.setFont(font2)
        self.song20.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")

        self.horizontalLayout_54.addWidget(self.song20)

        self.scrollArea_34.setWidget(self.scrollAreaWidgetContents_55)
        self.scrollArea_14 = QScrollArea(self.centralwidget)
        self.scrollArea_14.setObjectName(u"scrollArea_14")
        self.scrollArea_14.setGeometry(QRect(690, 85, 263, 66))
        sizePolicy.setHeightForWidth(self.scrollArea_14.sizePolicy().hasHeightForWidth())
        self.scrollArea_14.setSizePolicy(sizePolicy)
        self.scrollArea_14.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.scrollArea_14.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollArea_14.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea_14.setWidgetResizable(True)
        self.scrollAreaWidgetContents_19 = QWidget()
        self.scrollAreaWidgetContents_19.setObjectName(u"scrollAreaWidgetContents_19")
        self.scrollAreaWidgetContents_19.setGeometry(QRect(0, 0, 263, 45))
        self.horizontalLayout_19 = QHBoxLayout(self.scrollAreaWidgetContents_19)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName(u"horizontalLayout_19")
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.song13 = QLabel(self.scrollAreaWidgetContents_19)
        self.song13.setObjectName(u"song13")
        self.song13.setFont(font2)
        self.song13.setStyleSheet(u"background-color: rgb(255, 180, 0);\n"
"border: none;")
        self.song13.setWordWrap(False)

        self.horizontalLayout_19.addWidget(self.song13)

        self.scrollArea_14.setWidget(self.scrollAreaWidgetContents_19)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(-110, -30, 751, 551))
        self.label.setStyleSheet(u"background-color: rgb(255, 150, 0);\n"
"border: none;")
        MainWindow.setCentralWidget(self.centralwidget)
        self.label.raise_()
        self.buttons.raise_()
        self.scrollArea.raise_()
        self.scrollArea_12.raise_()
        self.num.raise_()
        self.num_3.raise_()
        self.num_2.raise_()
        self.scrollArea_25.raise_()
        self.num_4.raise_()
        self.scrollArea_2.raise_()
        self.num_5.raise_()
        self.scrollArea_26.raise_()
        self.num_6.raise_()
        self.scrollArea_3.raise_()
        self.num_7.raise_()
        self.scrollArea_27.raise_()
        self.num_8.raise_()
        self.scrollArea_4.raise_()
        self.num_9.raise_()
        self.scrollArea_28.raise_()
        self.num_10.raise_()
        self.scrollArea_5.raise_()
        self.scrollArea_29.raise_()
        self.num_11.raise_()
        self.scrollArea_6.raise_()
        self.num_12.raise_()
        self.num_13.raise_()
        self.num_14.raise_()
        self.scrollArea_7.raise_()
        self.scrollArea_30.raise_()
        self.scrollArea_8.raise_()
        self.scrollArea_13.raise_()
        self.num_15.raise_()
        self.num_16.raise_()
        self.scrollArea_31.raise_()
        self.num_17.raise_()
        self.num_18.raise_()
        self.num_19.raise_()
        self.num_20.raise_()
        self.num_21.raise_()
        self.scrollArea_32.raise_()
        self.scrollArea_33.raise_()
        self.num_22.raise_()
        self.scrollArea_9.raise_()
        self.scrollArea_10.raise_()
        self.scrollArea_11.raise_()
        self.num_23.raise_()
        self.num_24.raise_()
        self.scrollArea_34.raise_()
        self.scrollArea_14.raise_()

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.buttonforward.setText("")
        self.buttonbackward.setText("")
        self.button5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.button0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.button4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.button9.setText(QCoreApplication.translate("MainWindow", u"9", None))
        self.button3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.button8.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.button2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.button1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.button6.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.button7.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.song0.setText(QCoreApplication.translate("MainWindow", u"SONG NAME", None))
        self.song6.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.num.setText(QCoreApplication.translate("MainWindow", u"07: ", None))
        self.num_3.setText(QCoreApplication.translate("MainWindow", u"01: ", None))
        self.num_2.setText(QCoreApplication.translate("MainWindow", u"08: ", None))
        self.song7.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.num_4.setText(QCoreApplication.translate("MainWindow", u"02: ", None))
        self.song1.setText(QCoreApplication.translate("MainWindow", u"SONG NAME", None))
        self.num_5.setText(QCoreApplication.translate("MainWindow", u"09: ", None))
        self.song8.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.num_6.setText(QCoreApplication.translate("MainWindow", u"03: ", None))
        self.song2.setText(QCoreApplication.translate("MainWindow", u"SONG NAME", None))
        self.num_7.setText(QCoreApplication.translate("MainWindow", u"10:", None))
        self.song9.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.num_8.setText(QCoreApplication.translate("MainWindow", u"04:", None))
        self.song3.setText(QCoreApplication.translate("MainWindow", u"SONG NAME", None))
        self.num_9.setText(QCoreApplication.translate("MainWindow", u"11:", None))
        self.song10.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.num_10.setText(QCoreApplication.translate("MainWindow", u"05:", None))
        self.song4.setText(QCoreApplication.translate("MainWindow", u"SONG NAME", None))
        self.song11.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.num_11.setText(QCoreApplication.translate("MainWindow", u"06:", None))
        self.song5.setText(QCoreApplication.translate("MainWindow", u"SONG NAME", None))
        self.num_12.setText(QCoreApplication.translate("MainWindow", u"12:", None))
        self.num_13.setText(QCoreApplication.translate("MainWindow", u"16:", None))
        self.num_14.setText(QCoreApplication.translate("MainWindow", u"15:", None))
        self.song14.setText(QCoreApplication.translate("MainWindow", u"SONG NAME", None))
        self.song21.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song17.setText(QCoreApplication.translate("MainWindow", u"SONG NAME", None))
        self.song18.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.num_15.setText(QCoreApplication.translate("MainWindow", u"21:", None))
        self.num_16.setText(QCoreApplication.translate("MainWindow", u"24:", None))
        self.song22.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.num_17.setText(QCoreApplication.translate("MainWindow", u"13:", None))
        self.num_18.setText(QCoreApplication.translate("MainWindow", u"18:", None))
        self.num_19.setText(QCoreApplication.translate("MainWindow", u"23:", None))
        self.num_20.setText(QCoreApplication.translate("MainWindow", u"17:", None))
        self.num_21.setText(QCoreApplication.translate("MainWindow", u"14:", None))
        self.song23.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song19.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.num_22.setText(QCoreApplication.translate("MainWindow", u"22:", None))
        self.song12.setText(QCoreApplication.translate("MainWindow", u"SONG NAME", None))
        self.song15.setText(QCoreApplication.translate("MainWindow", u"SONG NAME", None))
        self.song16.setText(QCoreApplication.translate("MainWindow", u"SONG NAME", None))
        self.num_23.setText(QCoreApplication.translate("MainWindow", u"19:", None))
        self.num_24.setText(QCoreApplication.translate("MainWindow", u"20:", None))
        self.song20.setText(QCoreApplication.translate("MainWindow", u"Song Name", None))
        self.song13.setText(QCoreApplication.translate("MainWindow", u"SONG NAME", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
    # retranslateUi

